# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TitolarioVoce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=30)),
                ("titolo", models.CharField(max_length=200)),
                (
                    "pattern_codice",
                    models.CharField(
                        default="{CLI}-{TIT}-{ANNO}-{SEQ:03d}",
                        help_text="Pattern codice fascicolo: usa {CLI}, {TIT}, {ANNO}, {SEQ:03d}",
                        max_length=120,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figli",
                        to="titolario.titolariovoce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voce di titolario",
                "verbose_name_plural": "Voci di titolario",
                "db_table": "vocititolario",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="titolariovoce",
            constraint=models.UniqueConstraint(
                fields=("parent", "codice"), name="uniq_titolario_codice_per_parent"
            ),
        ),
    ]
