# Generated by Django 5.2.8 on 2026-01-21 07:36

import django.db.models.deletion
from django.db import migrations, models


def abilita_intestazione_su_voci_specifiche(apps, schema_editor):
    """
    Abilita il flag consente_intestazione su voci specifiche del titolario
    dove ha senso intestare sotto-voci ad anagrafiche
    """
    TitolarioVoce = apps.get_model("titolario", "TitolarioVoce")
    
    # Lista di codici voci che consentono intestazione
    voci_da_abilitare = [
        'HR-PERS',      # Dossier personale (dipendenti)
        'SALES-LEAD',   # Lead e opportunità (prospect/clienti)
        'LEG-CONT',     # Contenzioso (per singoli soggetti)
    ]
    
    updated_count = 0
    for codice in voci_da_abilitare:
        updated = TitolarioVoce.objects.filter(codice=codice).update(consente_intestazione=True)
        updated_count += updated
    
    if updated_count > 0:
        print(f"✓ Abilitata intestazione anagrafica su {updated_count} voci del titolario")


def reverse_abilita_intestazione(apps, schema_editor):
    """Rollback: disabilita flag su tutte le voci"""
    TitolarioVoce = apps.get_model("titolario", "TitolarioVoce")
    TitolarioVoce.objects.all().update(consente_intestazione=False)


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0009_anagrafica_denominazione_abbreviata"),
        ("titolario", "0002_titolario_privato"),
    ]

    operations = [
        migrations.AddField(
            model_name="titolariovoce",
            name="anagrafica",
            field=models.ForeignKey(
                blank=True,
                help_text="Anagrafica a cui è intestata questa voce (opzionale)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voci_titolario",
                to="anagrafiche.anagrafica",
                verbose_name="Anagrafica intestataria",
            ),
        ),
        migrations.AddField(
            model_name="titolariovoce",
            name="consente_intestazione",
            field=models.BooleanField(
                default=False,
                help_text="Se True, consente di creare sotto-voci intestate ad anagrafiche",
                verbose_name="Consente intestazione",
            ),
        ),
        migrations.AlterField(
            model_name="titolariovoce",
            name="pattern_codice",
            field=models.CharField(
                default="{CLI}-{TIT}-{ANNO}-{SEQ:03d}",
                help_text="Pattern codice fascicolo: usa {CLI}, {TIT}, {ANNO}, {SEQ:03d}, {ANA}",
                max_length=120,
            ),
        ),
        # Data migration: abilita flag su voci specifiche
        migrations.RunPython(
            abilita_intestazione_su_voci_specifiche,
            reverse_abilita_intestazione
        ),
    ]
