# Generated by Django 5.2.8 on 2026-03-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafiche", "0009_anagrafica_denominazione_abbreviata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Amministratore"),
                            ("MANAGER", "Manager"),
                            ("OPERATORE", "Operatore"),
                            ("VIEWER", "Visualizzatore"),
                        ],
                        db_index=True,
                        default="VIEWER",
                        max_length=20,
                        verbose_name="Ruolo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "assigned_clients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clienti visibili per OPERATORE/VIEWER. Vuoto = tutti i clienti (ADMIN/MANAGER)",
                        related_name="assigned_users",
                        to="anagrafiche.cliente",
                        verbose_name="Clienti Assegnati",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profilo Utente",
                "verbose_name_plural": "Profili Utente",
                "ordering": ["user__username"],
            },
        ),
    ]
