# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafiche", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pratica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(blank=True, max_length=60, unique=True)),
                ("oggetto", models.CharField(max_length=255)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("aperta", "Aperta"),
                            ("lavorazione", "In lavorazione"),
                            ("attesa", "In attesa"),
                            ("chiusa", "Chiusa"),
                        ],
                        db_index=True,
                        default="aperta",
                        max_length=20,
                    ),
                ),
                (
                    "periodo_riferimento",
                    models.CharField(
                        choices=[
                            ("anno", "Anno (YYYY)"),
                            ("annomese", "Anno-Mese (YYYYMM)"),
                            ("annomesegiorno", "Anno-Mese-Giorno (YYYYMMDD)"),
                        ],
                        db_index=True,
                        default="anno",
                        max_length=20,
                    ),
                ),
                (
                    "data_riferimento",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "periodo_key",
                    models.CharField(db_index=True, editable=False, max_length=8),
                ),
                ("progressivo", models.PositiveIntegerField(default=0, editable=False)),
                ("data_apertura", models.DateField(auto_now_add=True)),
                ("data_chiusura", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("tag", models.CharField(blank=True, max_length=200)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pratiche",
                        to="anagrafiche.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pratica",
                "verbose_name_plural": "Pratiche",
                "ordering": ["-data_apertura", "codice"],
            },
        ),
        migrations.CreateModel(
            name="PraticheTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(db_index=True, max_length=20, unique=True)),
                ("nome", models.CharField(max_length=120)),
                ("prefisso_codice", models.CharField(blank=True, max_length=20)),
                (
                    "pattern_codice",
                    models.CharField(
                        default="{CLI}-{TIPO}-{PER}-{SEQ:04d}",
                        help_text="Pattern del codice: usa {CLI}, {TIPO}, {PER}, {SEQ:04d}",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo pratica",
                "verbose_name_plural": "Tipi pratica",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="PraticaRelazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("dipendenza", "Dipendenza"),
                            ("collaborazione", "Collaborazione"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relazioni_entrata",
                        to="pratiche.pratica",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relazioni_uscita",
                        to="pratiche.pratica",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pratica",
            name="figli",
            field=models.ManyToManyField(
                blank=True,
                related_name="genitori",
                through="pratiche.PraticaRelazione",
                to="pratiche.pratica",
            ),
        ),
        migrations.AddField(
            model_name="pratica",
            name="responsabile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pratiche",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pratica",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pratiche",
                to="pratiche.pratichetipo",
            ),
        ),
        migrations.AddIndex(
            model_name="praticarelazione",
            index=models.Index(
                fields=["parent"], name="pratiche_pr_parent__d134da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="praticarelazione",
            index=models.Index(fields=["child"], name="pratiche_pr_child_i_9689e2_idx"),
        ),
        migrations.AddConstraint(
            model_name="praticarelazione",
            constraint=models.UniqueConstraint(
                fields=("parent", "child", "tipo"),
                name="uniq_relazione_parent_child_tipo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="praticarelazione",
            unique_together={("parent", "child")},
        ),
        migrations.AddIndex(
            model_name="pratica",
            index=models.Index(
                fields=["cliente", "tipo", "periodo_key"],
                name="pratiche_pr_cliente_d58573_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pratica",
            index=models.Index(fields=["stato"], name="pratiche_pr_stato_529f58_idx"),
        ),
        migrations.AddConstraint(
            model_name="pratica",
            constraint=models.UniqueConstraint(
                fields=("cliente", "tipo", "periodo_key", "progressivo"),
                name="uniq_pratica_gruppo_prog",
            ),
        ),
    ]
