# Generated by Django 4.2.16 on 2025-10-21 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pratiche", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scadenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True)),
                ("scadenza_at", models.DateTimeField(db_index=True)),
                (
                    "alert_offset_min",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="Minuti di anticipo per l'alert rispetto alla scadenza.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("alert_at", models.DateTimeField(db_index=True, editable=False)),
                (
                    "alert_method",
                    models.CharField(
                        choices=[("email", "Email"), ("webhook", "Webhook")],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "alert_email_to",
                    models.CharField(
                        blank=True,
                        help_text="Destinatari email separati da virgola (se vuoto, si usa la configurazione predefinita).",
                        max_length=500,
                    ),
                ),
                ("alert_webhook_url", models.URLField(blank=True)),
                ("alert_inviato_il", models.DateTimeField(blank=True, null=True)),
                (
                    "completata",
                    models.BooleanField(
                        default=False,
                        help_text="Marca la scadenza come gestita/chiusa.",
                    ),
                ),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                (
                    "pratica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scadenze",
                        to="pratiche.pratica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scadenza",
                "verbose_name_plural": "Scadenze",
                "ordering": ["-scadenza_at"],
                "indexes": [
                    models.Index(
                        fields=["pratica", "scadenza_at"],
                        name="pratiche_sc_pratica_e35947_idx",
                    ),
                    models.Index(
                        fields=["alert_at"], name="pratiche_sc_alert_a_debe1d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scadenza",
            constraint=models.CheckConstraint(
                check=models.Q(("alert_offset_min__gte", 0)),
                name="chk_alert_offset_min_non_neg",
            ),
        ),
    ]
