# Generated by Django 4.2.16 on 2025-10-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0004_anagrafica_codice"),
        ("pratiche", "0002_scadenza_scadenza_chk_alert_offset_min_non_neg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pratica",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pratiche",
                to="anagrafiche.cliente",
            ),
        ),
    ]
