# Generated by Django 4.2.16 on 2025-10-22 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pratiche", "0004_scadenza_alerts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scadenzaalert",
            options={
                "ordering": ["alert_at"],
                "verbose_name": "Alert scadenza",
                "verbose_name_plural": "Alert scadenza",
            },
        ),
        migrations.AlterField(
            model_name="scadenza",
            name="alert_email_to",
            field=models.CharField(
                blank=True, help_text="Legacy: destinatari email.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="scadenza",
            name="alert_offset_min",
            field=models.PositiveIntegerField(
                default=1440,
                help_text="Legacy: minuti di anticipo (usa gli alert multipli sotto).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="scadenzaalert",
            name="email_to",
            field=models.CharField(
                blank=True,
                help_text="Destinatari email separati da virgola.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="scadenzaalert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scadenzaalert",
            name="valore",
            field=models.PositiveIntegerField(
                help_text="Valore dell’offset nell’unità selezionata.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="scadenzaalert",
            index=models.Index(
                fields=["scadenza", "alert_at"], name="pratiche_sc_scadenz_1334c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scadenzaalert",
            index=models.Index(fields=["attivo"], name="pratiche_sc_attivo_3d2e94_idx"),
        ),
    ]
