# Generated by Django 4.2.16 on 2025-10-24 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pratiche", "0005_alter_scadenzaalert_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PraticaNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("memo", "Memo"),
                            ("comunicazione", "Comunicazione"),
                            ("chiusura", "Chiusura"),
                            ("altro", "Altro"),
                        ],
                        default="memo",
                        max_length=32,
                    ),
                ),
                ("testo", models.TextField()),
                ("data", models.DateField(default=django.utils.timezone.now)),
                (
                    "stato",
                    models.CharField(
                        choices=[("aperta", "Aperta"), ("chiusa", "Chiusa")],
                        default="aperta",
                        max_length=16,
                    ),
                ),
                (
                    "pratica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_collegate",
                        to="pratiche.pratica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota pratica",
                "verbose_name_plural": "Note pratica",
                "ordering": ["-data", "-id"],
                "indexes": [
                    models.Index(
                        fields=["pratica", "data"],
                        name="pratiche_pr_pratica_8e6dd7_idx",
                    )
                ],
            },
        ),
    ]
