# Generated by Django 4.2.16 on 2025-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pratiche", "0006_praticanota"),
    ]

    operations = [
        migrations.AddField(
            model_name="pratica",
            name="genitori",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pratiche da cui questa dipende o a cui è collegata come figlia.",
                related_name="pratiche_figlie",
                through="pratiche.PraticaRelazione",
                to="pratiche.pratica",
            ),
        ),
        migrations.AlterField(
            model_name="pratica",
            name="figli",
            field=models.ManyToManyField(
                blank=True,
                related_name="pratiche_genitrici",
                through="pratiche.PraticaRelazione",
                to="pratiche.pratica",
            ),
        ),
    ]
