# Generated by Django 4.2.16 on 2025-11-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pratiche", "0007_pratica_genitori_alter_pratica_figli"),
        ("scadenze", "0002_migrate_pratiche_scadenze"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scadenzaalert",
            name="scadenza",
        ),
        migrations.DeleteModel(
            name="Scadenza",
        ),
        migrations.DeleteModel(
            name="ScadenzaAlert",
        ),
    ]
