# Generated by Django 5.2.8 on 2025-11-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pratiche", "0008_remove_scadenzaalert_scadenza_delete_scadenza_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pratica",
            name="figli",
            field=models.ManyToManyField(
                blank=True,
                related_name="pratiche_genitrici",
                through="pratiche.PraticaRelazione",
                through_fields=("parent", "child"),
                to="pratiche.pratica",
            ),
        ),
    ]
