# Generated by Django 5.2.8 on 2026-02-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafiche", "0009_anagrafica_denominazione_abbreviata"),
        ("documenti", "0012_configure_bpag_duplicate_detection"),
        ("fascicoli", "0008_fascicolo_fascicoli_collegati"),
        ("titolario", "0003_titolariovoce_anagrafica_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "directory_path",
                    models.CharField(
                        help_text="Path assoluto o UNC della directory da scansionare",
                        max_length=500,
                        verbose_name="Percorso directory",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa"),
                            ("running", "In esecuzione"),
                            ("completed", "Completato"),
                            ("failed", "Fallito"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Avviato il"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completato il"
                    ),
                ),
                (
                    "total_files",
                    models.IntegerField(default=0, verbose_name="Totale file"),
                ),
                (
                    "processed_files",
                    models.IntegerField(default=0, verbose_name="File processati"),
                ),
                (
                    "successful_files",
                    models.IntegerField(
                        default=0, verbose_name="File classificati con successo"
                    ),
                ),
                (
                    "failed_files",
                    models.IntegerField(default=0, verbose_name="File falliti"),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista di errori occorsi durante l'elaborazione",
                        verbose_name="Errori",
                    ),
                ),
                (
                    "use_llm",
                    models.BooleanField(
                        default=True,
                        help_text="Se attivo, usa LLM per classificare file ambigui",
                        verbose_name="Usa LLM",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="openai",
                        help_text="Provider LLM da utilizzare (openai, anthropic, local)",
                        max_length=50,
                        verbose_name="Provider LLM",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Classificazione",
                "verbose_name_plural": "Jobs Classificazione",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path assoluto o relativo del file originale",
                        max_length=500,
                        verbose_name="Percorso file",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nome file"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Dimensione (bytes)"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME type"),
                ),
                (
                    "predicted_type",
                    models.CharField(
                        choices=[
                            ("CED", "Cedolino"),
                            ("UNI", "Unilav"),
                            ("DIC", "Dichiarazione Fiscale"),
                            ("BIL", "Bilancio"),
                            ("F24", "F24"),
                            ("EST", "Estratto Conto"),
                            ("FAT", "Fattura"),
                            ("CON", "Contratto"),
                            ("COR", "Corrispondenza"),
                            ("PRO", "Protocollo"),
                            ("ALT", "Altro"),
                        ],
                        max_length=10,
                        verbose_name="Tipo predetto",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "Alta (>80%)"),
                            ("medium", "Media (50-80%)"),
                            ("low", "Bassa (<50%)"),
                        ],
                        max_length=20,
                        verbose_name="Livello confidenza",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Valore da 0.0 a 1.0", verbose_name="Score confidenza"
                    ),
                ),
                (
                    "classification_method",
                    models.CharField(
                        default="rule",
                        help_text="Metodo usato: rule (pattern), llm, manual",
                        max_length=50,
                        verbose_name="Metodo",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Testo estratto da PDF o OCR",
                        verbose_name="Testo estratto",
                    ),
                ),
                (
                    "extracted_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata come data, importo, CF, PIVA, etc.",
                        verbose_name="Metadata estratti",
                    ),
                ),
                (
                    "imported",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, il file è stato importato in app documenti",
                        verbose_name="Importato",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Importato il"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Note aggiuntive o correzioni manuali",
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documenti.documento",
                        verbose_name="Documento creato",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai_classifier.classificationjob",
                        verbose_name="Job",
                    ),
                ),
                (
                    "suggested_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anagrafiche.cliente",
                        verbose_name="Cliente suggerito",
                    ),
                ),
                (
                    "suggested_fascicolo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fascicoli.fascicolo",
                        verbose_name="Fascicolo suggerito",
                    ),
                ),
                (
                    "suggested_titolario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="titolario.titolariovoce",
                        verbose_name="Titolario suggerito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risultato Classificazione",
                "verbose_name_plural": "Risultati Classificazione",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassifierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Chiave API OpenAI (lasciare vuoto per usare env var)",
                        max_length=255,
                        verbose_name="OpenAI API Key",
                    ),
                ),
                (
                    "default_llm_provider",
                    models.CharField(
                        default="openai",
                        max_length=50,
                        verbose_name="Provider LLM di default",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Modello OpenAI da usare (es: gpt-4o-mini, gpt-4)",
                        max_length=100,
                        verbose_name="Modello LLM",
                    ),
                ),
                (
                    "llm_temperature",
                    models.FloatField(
                        default=0.1,
                        help_text="Temperatura per LLM (0.0 = deterministico, 1.0 = creativo)",
                        verbose_name="Temperature LLM",
                    ),
                ),
                (
                    "llm_max_tokens",
                    models.IntegerField(
                        default=500,
                        help_text="Massimo numero di token per risposta LLM",
                        verbose_name="Max tokens LLM",
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Soglia minima di confidenza per classificazione automatica",
                        verbose_name="Soglia confidenza",
                    ),
                ),
                (
                    "filename_patterns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dizionario {tipo: [pattern1, pattern2]} per matching filename. Es: {'CED': ['cedolino', 'payslip'], 'UNI': ['unilav', 'comunicazione']}",
                        verbose_name="Pattern filename",
                    ),
                ),
                (
                    "content_patterns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dizionario {tipo: [keyword1, keyword2]} per matching testo estratto. Es: {'F24': ['modello f24', 'codice tributo'], 'BIL': ['bilancio', 'stato patrimoniale']}",
                        verbose_name="Pattern contenuto",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=50,
                        help_text="Dimensione massima file processabili in MB",
                        verbose_name="Dimensione max file (MB)",
                    ),
                ),
                (
                    "allowed_extensions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista estensioni file permesse (es: ['.pdf', '.jpg', '.png'])",
                        verbose_name="Estensioni permesse",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aggiornato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione Classificatore",
                "verbose_name_plural": "Configurazione Classificatore",
            },
        ),
        migrations.AddIndex(
            model_name="classificationjob",
            index=models.Index(
                fields=["status", "created_at"], name="ai_classifi_status_0af597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationjob",
            index=models.Index(
                fields=["created_by", "status"], name="ai_classifi_created_db5bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(
                fields=["job", "imported"], name="ai_classifi_job_id_71701b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(
                fields=["predicted_type", "confidence_level"],
                name="ai_classifi_predict_7ed084_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(
                fields=["suggested_cliente"], name="ai_classifi_suggest_7ebdf6_idx"
            ),
        ),
    ]
