# Generated by Django 5.2.8 on 2026-02-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_classifier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingExample",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_name",
                    models.CharField(
                        help_text="Nome del file di esempio",
                        max_length=255,
                        verbose_name="Nome file",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path assoluto del file di esempio",
                        max_length=500,
                        null=True,
                        verbose_name="Percorso file",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Codice tipo documento (es. CED, UNI, DIC)",
                        max_length=10,
                        verbose_name="Tipo documento",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Testo estratto dal documento",
                        verbose_name="Testo estratto",
                    ),
                ),
                (
                    "extracted_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata estratti"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione delle caratteristiche distintive del documento",
                        verbose_name="Descrizione",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se disattivato, l'esempio non viene usato nel training",
                        verbose_name="Attivo",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priorità dell'esempio (più alto = più importante)",
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_examples",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Esempio di Training",
                "verbose_name_plural": "Esempi di Training",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "is_active"],
                        name="ai_classifi_documen_568cd4_idx",
                    ),
                    models.Index(
                        fields=["-priority"], name="ai_classifi_priorit_c06ec4_idx"
                    ),
                ],
            },
        ),
    ]
