# Generated by Django 5.2.8 on 2026-02-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_classifier", "0002_trainingexample"),
        ("anagrafiche", "0009_anagrafica_denominazione_abbreviata"),
        ("documenti", "0012_configure_bpag_duplicate_detection"),
        ("titolario", "0003_titolariovoce_anagrafica_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Versione semantica (es. v1.0.0, v1.1.0)",
                        max_length=50,
                        unique=True,
                        verbose_name="Versione",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("logistic_regression", "Logistic Regression"),
                            ("svm", "SVM"),
                            ("naive_bayes", "Naive Bayes"),
                        ],
                        default="random_forest",
                        max_length=50,
                        verbose_name="Tipo modello",
                    ),
                ),
                (
                    "model_file_path",
                    models.CharField(
                        help_text="Path al file .pkl del modello su NAS",
                        max_length=500,
                        verbose_name="Path modello",
                    ),
                ),
                (
                    "vectorizer_file_path",
                    models.CharField(
                        help_text="Path al file .pkl del TF-IDF vectorizer su NAS",
                        max_length=500,
                        verbose_name="Path vectorizer",
                    ),
                ),
                (
                    "label_encoder_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path ai file .pkl dei label encoders (tipo, cliente, titolario)",
                        max_length=500,
                        verbose_name="Path label encoder",
                    ),
                ),
                ("accuracy", models.FloatField(verbose_name="Accuracy")),
                ("precision", models.FloatField(verbose_name="Precision")),
                ("recall", models.FloatField(verbose_name="Recall")),
                ("f1_score", models.FloatField(verbose_name="F1 Score")),
                (
                    "training_samples",
                    models.IntegerField(
                        help_text="Numero di documenti usati per il training",
                        verbose_name="Campioni training",
                    ),
                ),
                (
                    "training_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Distribuzione classi, parametri modello, etc.",
                        verbose_name="Statistiche training",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Solo un modello può essere attivo alla volta",
                        verbose_name="Attivo",
                    ),
                ),
                (
                    "trained_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Addestrato il"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Attivato il"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Note sul training, cambiamenti, esperimenti",
                        verbose_name="Note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modello ML",
                "verbose_name_plural": "Modelli ML",
                "ordering": ["-trained_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-trained_at"],
                        name="ai_classifi_is_acti_959e03_idx",
                    ),
                    models.Index(
                        fields=["version"], name="ai_classifi_version_c4c941_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=500, verbose_name="Filename originale"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 del contenuto per deduplica",
                        max_length=64,
                        verbose_name="Hash file",
                    ),
                ),
                (
                    "predicted_data_documento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data documento predetta"
                    ),
                ),
                (
                    "predicted_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Importi, numeri documento, CF, P.IVA, etc.",
                        verbose_name="Altri metadata predetti",
                    ),
                ),
                (
                    "type_confidence",
                    models.FloatField(
                        help_text="Score 0-1 per il tipo documento",
                        verbose_name="Confidence tipo",
                    ),
                ),
                (
                    "cliente_confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confidence cliente"
                    ),
                ),
                (
                    "titolario_confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Confidence titolario"
                    ),
                ),
                (
                    "user_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="True se l'utente ha accettato tutte le predizioni",
                        verbose_name="Utente ha confermato",
                    ),
                ),
                (
                    "user_corrected",
                    models.BooleanField(
                        default=False,
                        help_text="True se l'utente ha modificato almeno una predizione",
                        verbose_name="Utente ha corretto",
                    ),
                ),
                (
                    "correction_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dettaglio delle correzioni: {campo: {predicted: X, actual: Y}}",
                        verbose_name="Dati correzione",
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "Corretto"),
                            ("incorrect", "Errato"),
                            ("partially_correct", "Parzialmente corretto"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Feedback utente",
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True,
                        help_text="Note libere dell'utente sul risultato",
                        verbose_name="Note utente",
                    ),
                ),
                (
                    "extracted_features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="TF-IDF vector, NER entities, patterns matched, etc.",
                        verbose_name="Features estratte",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "feedback_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Feedback ricevuto il"
                    ),
                ),
                (
                    "used_for_training",
                    models.BooleanField(
                        default=False,
                        help_text="True se questo esempio è stato incluso in un re-training",
                        verbose_name="Usato per training",
                    ),
                ),
                (
                    "documento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_prediction",
                        to="documenti.documento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "predicted_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_predictions",
                        to="anagrafiche.cliente",
                        verbose_name="Cliente predetto",
                    ),
                ),
                (
                    "predicted_titolario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_predictions",
                        to="titolario.titolariovoce",
                        verbose_name="Titolario predetto",
                    ),
                ),
                (
                    "predicted_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_predictions",
                        to="documenti.documentitipo",
                        verbose_name="Tipo predetto",
                    ),
                ),
                (
                    "ml_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predictions",
                        to="ai_classifier.mlmodel",
                        verbose_name="Modello ML",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predizione Documento",
                "verbose_name_plural": "Predizioni Documenti",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Avviato il"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completato il"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "In esecuzione"),
                            ("completed", "Completato"),
                            ("failed", "Fallito"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "training_samples_count",
                    models.IntegerField(
                        default=0,
                        help_text="Numero totale di documenti usati (vecchi + nuovi)",
                        verbose_name="Campioni training",
                    ),
                ),
                (
                    "new_samples_count",
                    models.IntegerField(
                        default=0,
                        help_text="Numero di nuovi documenti dalla coda",
                        verbose_name="Nuovi campioni",
                    ),
                ),
                (
                    "accuracy_improvement",
                    models.FloatField(
                        blank=True,
                        help_text="Differenza accuracy: nuovo modello - vecchio modello",
                        null=True,
                        verbose_name="Miglioramento accuracy",
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True,
                        help_text="Log completo dell'esecuzione training",
                        verbose_name="Log",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="Errori"),
                ),
                (
                    "new_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_jobs",
                        to="ai_classifier.mlmodel",
                        verbose_name="Nuovo modello",
                    ),
                ),
                (
                    "previous_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_for_jobs",
                        to="ai_classifier.mlmodel",
                        verbose_name="Modello precedente",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null se automatico (cron)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Avviato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Training",
                "verbose_name_plural": "Jobs Training",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Accodato il"),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="True se incluso in un training job",
                        verbose_name="Processato",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processato il"
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_queue_entries",
                        to="ai_classifier.documentprediction",
                        verbose_name="Predizione",
                    ),
                ),
                (
                    "training_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_entries",
                        to="ai_classifier.trainingjob",
                        verbose_name="Job training",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coda Training",
                "verbose_name_plural": "Code Training",
                "ordering": ["queued_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentprediction",
            index=models.Index(
                fields=["file_hash"], name="ai_classifi_file_ha_cab16a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentprediction",
            index=models.Index(
                fields=["user_feedback", "used_for_training"],
                name="ai_classifi_user_fe_46a212_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentprediction",
            index=models.Index(
                fields=["ml_model", "-created_at"],
                name="ai_classifi_ml_mode_b51fbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentprediction",
            index=models.Index(
                fields=["-type_confidence"], name="ai_classifi_type_co_0d02b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["status", "-started_at"], name="ai_classifi_status_fa1993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingqueue",
            index=models.Index(
                fields=["processed", "queued_at"], name="ai_classifi_process_5b7fd8_idx"
            ),
        ),
    ]
