# Generated by Django 5.2.8 on 2026-02-27 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_classifier",
            "0003_mlmodel_documentprediction_trainingjob_trainingqueue_and_more",
        ),
        ("documenti", "0012_configure_bpag_duplicate_detection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPredictionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_predizione",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Probabilità della predizione (0-1)",
                        max_digits=5,
                        verbose_name="Confidence Predizione",
                    ),
                ),
                (
                    "top_3_predizioni",
                    models.JSONField(
                        default=list,
                        help_text="Lista delle 3 predizioni più probabili con confidence",
                        verbose_name="Top 3 Predizioni",
                    ),
                ),
                (
                    "predizione_corretta",
                    models.BooleanField(
                        help_text="True se tipo_predetto == tipo_confermato",
                        verbose_name="Predizione Corretta",
                    ),
                ),
                (
                    "dati_estratti_ai",
                    models.JSONField(
                        default=dict,
                        help_text="Dati estratti automaticamente dall'AI",
                        verbose_name="Dati Estratti AI",
                    ),
                ),
                (
                    "data_predizione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Predizione"
                    ),
                ),
                (
                    "usato_per_training",
                    models.BooleanField(
                        default=False,
                        help_text="True se questo feedback è già stato usato per il re-training",
                        verbose_name="Usato per Training",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback",
                        to="documenti.documento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "tipo_confermato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conferme_utente",
                        to="documenti.documentitipo",
                        verbose_name="Tipo Confermato Utente",
                    ),
                ),
                (
                    "tipo_predetto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predizioni_ai",
                        to="documenti.documentitipo",
                        verbose_name="Tipo Predetto AI",
                    ),
                ),
                (
                    "training_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_usati",
                        to="ai_classifier.trainingjob",
                        verbose_name="Training Job",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        help_text="Utente che ha confermato il tipo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Predizione AI",
                "verbose_name_plural": "Feedback Predizioni AI",
                "ordering": ["-data_predizione"],
            },
        ),
        migrations.CreateModel(
            name="DocumentExtractionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome descrittivo del template (es. 'UNILAV Standard 2026')",
                        max_length=200,
                        verbose_name="Nome Template",
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione dettagliata del template e quando usarlo",
                        verbose_name="Descrizione",
                    ),
                ),
                (
                    "numero_pagine",
                    models.IntegerField(
                        default=1,
                        help_text="Numero di pagine del template",
                        verbose_name="Numero Pagine",
                    ),
                ),
                (
                    "attivo",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, il template non verrà usato per l'estrazione",
                        verbose_name="Attivo",
                    ),
                ),
                (
                    "priorita",
                    models.IntegerField(
                        default=0,
                        help_text="Ordine di preferenza (maggiore = più priorità)",
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "creato_il",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "aggiornato_il",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_creati",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_templates",
                        to="documenti.documentitipo",
                        verbose_name="Tipo Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Estrazione",
                "verbose_name_plural": "Template Estrazione",
                "ordering": ["-priorita", "-creato_il"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_campo",
                    models.CharField(
                        help_text="Nome del campo corretto",
                        max_length=100,
                        verbose_name="Nome Campo",
                    ),
                ),
                (
                    "valore_estratto",
                    models.TextField(
                        help_text="Valore estratto automaticamente",
                        verbose_name="Valore Estratto AI",
                    ),
                ),
                (
                    "valore_corretto",
                    models.TextField(
                        help_text="Valore corretto dall'utente",
                        verbose_name="Valore Corretto Utente",
                    ),
                ),
                (
                    "confidence_estrazione",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Confidence dell'estrazione OCR (se disponibile)",
                        max_digits=5,
                        null=True,
                        verbose_name="Confidence Estrazione",
                    ),
                ),
                (
                    "data_correzione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Correzione"
                    ),
                ),
                (
                    "usato_per_training",
                    models.BooleanField(
                        default=False, verbose_name="Usato per Training"
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correzioni",
                        to="ai_classifier.aipredictionfeedback",
                        verbose_name="Feedback AI",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correzione Estrazione",
                "verbose_name_plural": "Correzioni Estrazione",
                "ordering": ["-data_correzione"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_campo_template",
                    models.CharField(
                        help_text="Nome del campo nel template (deve corrispondere a una zona)",
                        max_length=100,
                        verbose_name="Nome Campo Template",
                    ),
                ),
                (
                    "tipo_campo_destinazione",
                    models.CharField(
                        choices=[
                            ("field", "Campo Modello"),
                            ("attribute", "Attributo Dinamico"),
                            ("note", "Note"),
                            ("metadata", "Metadata"),
                        ],
                        max_length=20,
                        verbose_name="Tipo Campo Destinazione",
                    ),
                ),
                (
                    "nome_campo_destinazione",
                    models.CharField(
                        help_text="Nome del campo nel modello (es. 'data_documento', 'cliente.codice_fiscale', 'attributo:retribuzione')",
                        max_length=200,
                        verbose_name="Nome Campo Destinazione",
                    ),
                ),
                (
                    "funzione_trasformazione",
                    models.CharField(
                        blank=True,
                        help_text="Nome funzione per trasformare il dato (es. 'parse_date_it', 'normalize_cf')",
                        max_length=100,
                        verbose_name="Funzione Trasformazione",
                    ),
                ),
                (
                    "formato_input",
                    models.CharField(
                        blank=True,
                        help_text="Formato del dato estratto (es. 'DD/MM/YYYY' per date)",
                        max_length=100,
                        verbose_name="Formato Input",
                    ),
                ),
                (
                    "valore_default",
                    models.CharField(
                        blank=True,
                        help_text="Valore da usare se l'estrazione fallisce",
                        max_length=500,
                        verbose_name="Valore Default",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_campi",
                        to="ai_classifier.documentextractiontemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping Campo",
                "verbose_name_plural": "Mapping Campi",
                "ordering": ["template", "nome_campo_template"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionTemplatePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pagina",
                    models.IntegerField(
                        help_text="Numero progressivo della pagina (1-based)",
                        verbose_name="Numero Pagina",
                    ),
                ),
                (
                    "immagine_template",
                    models.ImageField(
                        help_text="Immagine della pagina con zone evidenziate",
                        upload_to="extraction_templates/%Y/%m/",
                        verbose_name="Immagine Template",
                    ),
                ),
                (
                    "larghezza",
                    models.IntegerField(
                        help_text="Larghezza dell'immagine template in pixel",
                        verbose_name="Larghezza (px)",
                    ),
                ),
                (
                    "altezza",
                    models.IntegerField(
                        help_text="Altezza dell'immagine template in pixel",
                        verbose_name="Altezza (px)",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagine",
                        to="ai_classifier.documentextractiontemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagina Template",
                "verbose_name_plural": "Pagine Template",
                "ordering": ["template", "numero_pagina"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionTemplateZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_campo",
                    models.CharField(
                        help_text="Nome identificativo del campo da estrarre (es. 'codice_fiscale_datore')",
                        max_length=100,
                        verbose_name="Nome Campo",
                    ),
                ),
                (
                    "etichetta",
                    models.CharField(
                        help_text="Etichetta human-readable (es. 'Codice Fiscale Datore di Lavoro')",
                        max_length=200,
                        verbose_name="Etichetta",
                    ),
                ),
                (
                    "x_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Posizione X in percentuale (0-100)",
                        max_digits=5,
                        verbose_name="X (%)",
                    ),
                ),
                (
                    "y_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Posizione Y in percentuale (0-100)",
                        max_digits=5,
                        verbose_name="Y (%)",
                    ),
                ),
                (
                    "width_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Larghezza in percentuale (0-100)",
                        max_digits=5,
                        verbose_name="Larghezza (%)",
                    ),
                ),
                (
                    "height_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Altezza in percentuale (0-100)",
                        max_digits=5,
                        verbose_name="Altezza (%)",
                    ),
                ),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("text", "Testo"),
                            ("codice_fiscale", "Codice Fiscale"),
                            ("partita_iva", "Partita IVA"),
                            ("date", "Data"),
                            ("decimal", "Numero Decimale"),
                            ("integer", "Numero Intero"),
                            ("email", "Email"),
                            ("phone", "Telefono"),
                            ("currency", "Importo Valuta"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Tipo Dato",
                    ),
                ),
                (
                    "obbligatorio",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, l'estrazione fallisce se questo campo è vuoto",
                        verbose_name="Obbligatorio",
                    ),
                ),
                (
                    "pattern_validazione",
                    models.CharField(
                        blank=True,
                        help_text="Espressione regolare per validare il dato estratto (opzionale)",
                        max_length=500,
                        verbose_name="Pattern Validazione",
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(
                        default=0,
                        help_text="Ordine di visualizzazione nel form",
                        verbose_name="Ordine",
                    ),
                ),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone",
                        to="ai_classifier.extractiontemplatepage",
                        verbose_name="Pagina Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona Estrazione",
                "verbose_name_plural": "Zone Estrazione",
                "ordering": ["pagina", "ordine", "nome_campo"],
            },
        ),
        migrations.AddIndex(
            model_name="aipredictionfeedback",
            index=models.Index(
                fields=["-data_predizione"], name="ai_classifi_data_pr_35575d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aipredictionfeedback",
            index=models.Index(
                fields=["predizione_corretta"], name="ai_classifi_predizi_2cd466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aipredictionfeedback",
            index=models.Index(
                fields=["usato_per_training"], name="ai_classifi_usato_p_d3d88e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentextractiontemplate",
            unique_together={("tipo_documento", "nome")},
        ),
        migrations.AddIndex(
            model_name="extractioncorrection",
            index=models.Index(
                fields=["nome_campo"], name="ai_classifi_nome_ca_1784da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractioncorrection",
            index=models.Index(
                fields=["usato_per_training"], name="ai_classifi_usato_p_b5bf9a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="extractionfieldmapping",
            unique_together={("template", "nome_campo_template")},
        ),
        migrations.AlterUniqueTogether(
            name="extractiontemplatepage",
            unique_together={("template", "numero_pagina")},
        ),
        migrations.AlterUniqueTogether(
            name="extractiontemplatezone",
            unique_together={("pagina", "nome_campo")},
        ),
    ]
