# Generated by Django 4.2.16 on 2026-04-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_classifier",
            "0004_aipredictionfeedback_documentextractiontemplate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classifierconfig",
            name="openai_api_key",
        ),
    ]
