# Generated by Django 4.2.16 on 2025-10-20 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafiche", "0003_alter_cliente_codice_destinatario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documenti", "0002_alter_protocollocounter_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolloCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField()),
                (
                    "direzione",
                    models.CharField(
                        choices=[("IN", "Entrata"), ("OUT", "Uscita")], max_length=3
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_counters",
                        to="anagrafiche.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contatore protocollo",
                "verbose_name_plural": "Contatori protocollo",
                "indexes": [
                    models.Index(
                        fields=["cliente", "anno", "direzione"],
                        name="protocollo__cliente_d81ebd_idx",
                    )
                ],
                "unique_together": {("cliente", "anno", "direzione")},
            },
        ),
        migrations.CreateModel(
            name="MovimentoProtocollo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direzione",
                    models.CharField(
                        choices=[("IN", "Entrata"), ("OUT", "Uscita")], max_length=3
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("anno", models.PositiveIntegerField(db_index=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "destinatario",
                    models.CharField(
                        blank=True,
                        help_text="A chi consegni in uscita / da chi ricevi in entrata",
                        max_length=255,
                    ),
                ),
                (
                    "chiuso",
                    models.BooleanField(
                        default=False, help_text="Per OUT: flaggato True quando rientra"
                    ),
                ),
                ("data_rientro_prevista", models.DateField(blank=True, null=True)),
                ("causale", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimenti",
                        to="anagrafiche.anagrafica",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimenti",
                        to="documenti.documento",
                    ),
                ),
                (
                    "operatore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rientro_di",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rientrato_con",
                        to="protocollo.movimentoprotocollo",
                    ),
                ),
                (
                    "ubicazione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collocazione fisica in entrata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documenti.ubicazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento di protocollo",
                "verbose_name_plural": "Movimenti di protocollo",
                "ordering": ["cliente", "anno", "direzione", "numero"],
                "indexes": [
                    models.Index(
                        fields=["documento", "direzione", "chiuso"],
                        name="protocollo__documen_9855b1_idx",
                    ),
                    models.Index(
                        fields=["cliente", "anno", "direzione", "numero"],
                        name="protocollo__cliente_a1ac45_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.UniqueConstraint(
                fields=("cliente", "anno", "direzione", "numero"),
                name="uniq_protocollo_per_cliente_anno_dir_num",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("direzione", "IN"), ("rientro_di__isnull", True), _connector="OR"
                ),
                name="rientro_di_solo_per_IN",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.CheckConstraint(
                check=models.Q(("numero__gt", 0)), name="numero_maggiore_zero"
            ),
        ),
    ]
