# Generated by Django 4.2.16 on 2025-10-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0004_ubicazione"),
        ("protocollo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentoprotocollo",
            name="ubicazione",
            field=models.ForeignKey(
                blank=True,
                help_text="Collocazione fisica in entrata",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archivio_fisico.ubicazione",
            ),
        ),
    ]
