# Generated by Django 4.2.16 on 2025-10-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fascicoli", "0001_initial"),
        ("documenti", "0002_alter_protocollocounter_unique_together_and_more"),
        ("protocollo", "0003_alter_movimentoprotocollo_ubicazione"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentoprotocollo",
            name="fascicolo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimenti_protocollo",
                to="fascicoli.fascicolo",
            ),
        ),
        migrations.AlterField(
            model_name="movimentoprotocollo",
            name="documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimenti",
                to="documenti.documento",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentoprotocollo",
            index=models.Index(
                fields=["fascicolo", "direzione", "chiuso"],
                name="protocollo__fascico_586876_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("documento__isnull", False), ("fascicolo__isnull", True)),
                    models.Q(("documento__isnull", True), ("fascicolo__isnull", False)),
                    _connector="OR",
                ),
                name="chk_one_target_set",
            ),
        ),
    ]
