# Generated by Django 5.2.8 on 2025-11-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_target_fields(apps, schema_editor):
    MovimentoProtocollo = apps.get_model('protocollo', 'MovimentoProtocollo')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Documento = apps.get_model('documenti', 'Documento')
    Fascicolo = apps.get_model('fascicoli', 'Fascicolo')

    content_type_cache = {}

    def get_ct(model):
        key = (model._meta.app_label, model._meta.model_name)
        if key not in content_type_cache:
            content_type_cache[key] = ContentType.objects.get(app_label=key[0], model=key[1])
        return content_type_cache[key]

    batch = []
    qs = MovimentoProtocollo.objects.select_related('documento', 'fascicolo').all().iterator()
    for movimento in qs:
        ct = None
        object_id = None
        label = ''
        tipo = ''

        if movimento.documento_id:
            ct = get_ct(Documento)
            object_id = str(movimento.documento_id)
            tipo = 'documento'
            documento = getattr(movimento, 'documento', None)
            label = str(documento) if documento else ''
        elif movimento.fascicolo_id:
            ct = get_ct(Fascicolo)
            object_id = str(movimento.fascicolo_id)
            tipo = 'fascicolo'
            fascicolo = getattr(movimento, 'fascicolo', None)
            label = str(fascicolo) if fascicolo else ''
        else:
            # Nessuna informazione: lasciare valori di default
            continue

        movimento.target_content_type = ct
        movimento.target_object_id = object_id
        movimento.target_tipo = tipo
        movimento.target_label = label
        batch.append(movimento)

        if len(batch) >= 200:
            MovimentoProtocollo.objects.bulk_update(batch, ['target_content_type', 'target_object_id', 'target_tipo', 'target_label'])
            batch.clear()

    if batch:
        MovimentoProtocollo.objects.bulk_update(batch, ['target_content_type', 'target_object_id', 'target_tipo', 'target_label'])


def noop_reverse(apps, schema_editor):
    """I campi restano valorizzati: nessuna operazione in rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0007_alter_indirizzo_provincia_comuneitaliano_and_more'),
        ('archivio_fisico', '0019_alter_operazionearchivio_verbale_scan_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documenti', '0005_filedeletionrequest'),
        ('fascicoli', '0007_alter_fascicolo_stato'),
        ('protocollo', '0004_movimentoprotocollo_fascicolo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimentoprotocollo',
            name='chk_one_target_set',
        ),
        migrations.RemoveIndex(
            model_name='movimentoprotocollo',
            name='protocollo__documen_9855b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentoprotocollo',
            name='protocollo__fascico_586876_idx',
        ),
        migrations.AddField(
            model_name='movimentoprotocollo',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='movimentoprotocollo',
            name='target_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimentoprotocollo',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='movimentoprotocollo',
            name='target_tipo',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='movimentoprotocollo',
            index=models.Index(fields=['target_tipo', 'target_content_type', 'target_object_id'], name='protocollo__target__b789f0_idx'),
        ),
        migrations.RunPython(populate_target_fields, noop_reverse),
        migrations.AddConstraint(
            model_name='movimentoprotocollo',
            constraint=models.CheckConstraint(check=~models.Q(documento__isnull=False, fascicolo__isnull=False), name='chk_doc_fascicolo_xor'),
        ),
        migrations.AddConstraint(
            model_name='movimentoprotocollo',
            constraint=models.CheckConstraint(check=(models.Q(documento__isnull=False) | models.Q(fascicolo__isnull=False) | models.Q(target_content_type__isnull=False)), name='chk_target_presente'),
        ),
    ]
