# Generated by Django 4.2.16 on 2025-11-11 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0002_migrate_pratiche_scadenze"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scadenza",
            options={
                "ordering": ["-aggiornato_il", "titolo"],
                "verbose_name": "Scadenza",
                "verbose_name_plural": "Scadenze",
            },
        ),
        migrations.AlterModelOptions(
            name="scadenzanotificalog",
            options={
                "ordering": ["-registrato_il"],
                "verbose_name": "Log notifica scadenza",
                "verbose_name_plural": "Log notifiche scadenze",
            },
        ),
        migrations.AlterModelOptions(
            name="scadenzaoccorrenza",
            options={
                "ordering": ["inizio"],
                "verbose_name": "Occorrenza scadenza",
                "verbose_name_plural": "Occorrenze scadenze",
            },
        ),
        migrations.AlterModelOptions(
            name="scadenzawebhookpayload",
            options={
                "ordering": ["-inviato_il"],
                "verbose_name": "Payload webhook scadenza",
                "verbose_name_plural": "Payload webhook scadenze",
            },
        ),
        migrations.RemoveConstraint(
            model_name="scadenza",
            name="scadenza_periodicita_intervallo_gte_1",
        ),
        migrations.RenameIndex(
            model_name="scadenza",
            new_name="scadenze_sc_stato_c1926d_idx",
            old_name="scadenza_stato_priorita_idx",
        ),
        migrations.RenameIndex(
            model_name="scadenza",
            new_name="scadenze_sc_creato__48f494_idx",
            old_name="scadenza_creato_il_idx",
        ),
        migrations.RenameIndex(
            model_name="scadenzanotificalog",
            new_name="scadenze_sc_evento_da64be_idx",
            old_name="occ_log_evento_idx",
        ),
        migrations.RenameIndex(
            model_name="scadenzaoccorrenza",
            new_name="scadenze_sc_scadenz_a34121_idx",
            old_name="occ_scadenza_inizio_idx",
        ),
        migrations.RenameIndex(
            model_name="scadenzaoccorrenza",
            new_name="scadenze_sc_stato_fcb41f_idx",
            old_name="occ_stato_idx",
        ),
        migrations.RenameIndex(
            model_name="scadenzaoccorrenza",
            new_name="scadenze_sc_alert_p_b48e44_idx",
            old_name="occ_alert_programmata_idx",
        ),
        migrations.AlterField(
            model_name="scadenza",
            name="periodicita_intervallo",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Intervallo della periodicità (es: ogni 2 settimane).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="scadenzaoccorrenza",
            name="offset_alert_minuti",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minuti di anticipo per la notifica.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
