# Generated by Django 5.2.8 on 2025-11-19 09:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0004_reset_scadenze_sequences"),
    ]

    operations = [
        migrations.AddField(
            model_name="scadenza",
            name="data_scadenza",
            field=models.DateField(
                blank=True,
                help_text="Data della prima occorrenza (se non specificata, usa la data attuale).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scadenza",
            name="num_occorrenze",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero massimo di occorrenze da generare (lascia vuoto per illimitate).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scadenzaoccorrenza",
            name="giornaliera",
            field=models.BooleanField(
                default=False,
                help_text="Se True, l'occorrenza occupa l'intera giornata (all-day event).",
            ),
        ),
        migrations.CreateModel(
            name="ScadenzaAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset_alert_periodo",
                    models.CharField(
                        choices=[
                            ("minutes", "Minuti"),
                            ("hours", "Ore"),
                            ("days", "Giorni"),
                            ("weeks", "Settimane"),
                        ],
                        default="days",
                        help_text="Unità di tempo per calcolare quando inviare l'alert.",
                        max_length=20,
                    ),
                ),
                (
                    "offset_alert",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numero di unità di tempo prima dell'occorrenza.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "metodo_alert",
                    models.CharField(
                        choices=[("email", "Email"), ("webhook", "Webhook")],
                        db_index=True,
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "alert_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurazione specifica per questo alert (destinatari, URL, etc.).",
                    ),
                ),
                (
                    "alert_programmata_il",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Momento calcolato in cui l'alert deve essere inviato.",
                        null=True,
                    ),
                ),
                ("alert_inviata_il", models.DateTimeField(blank=True, null=True)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa"),
                            ("scheduled", "Programmato"),
                            ("sent", "Inviato"),
                            ("failed", "Fallito"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                (
                    "occorrenza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="scadenze.scadenzaoccorrenza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert scadenza",
                "verbose_name_plural": "Alert scadenze",
                "ordering": ["alert_programmata_il"],
                "indexes": [
                    models.Index(
                        fields=["occorrenza", "stato"],
                        name="scadenze_sc_occorre_b89bb7_idx",
                    ),
                    models.Index(
                        fields=["alert_programmata_il", "stato"],
                        name="scadenze_sc_alert_p_b7aa9a_idx",
                    ),
                ],
            },
        ),
    ]
