# Generated by Django 5.2.8 on 2025-11-19 09:08

from django.db import migrations


def migrate_alerts_to_new_model(apps, schema_editor):
    """
    Migra gli alert esistenti (offset_alert_minuti) dal modello ScadenzaOccorrenza
    al nuovo modello ScadenzaAlert.
    """
    ScadenzaOccorrenza = apps.get_model("scadenze", "ScadenzaOccorrenza")
    ScadenzaAlert = apps.get_model("scadenze", "ScadenzaAlert")
    
    occorrenze_con_alert = ScadenzaOccorrenza.objects.exclude(
        offset_alert_minuti=0
    ).select_related('scadenza')
    
    alerts_to_create = []
    for occorrenza in occorrenze_con_alert:
        # Converti minuti in unità più appropriate
        minuti = occorrenza.offset_alert_minuti
        
        if minuti == 0:
            continue
            
        # Determina la migliore unità di tempo
        if minuti % (7 * 24 * 60) == 0:  # Settimane
            periodo = "weeks"
            offset = minuti // (7 * 24 * 60)
        elif minuti % (24 * 60) == 0:  # Giorni
            periodo = "days"
            offset = minuti // (24 * 60)
        elif minuti % 60 == 0:  # Ore
            periodo = "hours"
            offset = minuti // 60
        else:  # Minuti
            periodo = "minutes"
            offset = minuti
        
        # Copia la configurazione esistente
        alert_config = occorrenza.alert_config or {}
        
        alert = ScadenzaAlert(
            occorrenza=occorrenza,
            offset_alert_periodo=periodo,
            offset_alert=offset,
            metodo_alert=occorrenza.metodo_alert,
            alert_config=alert_config,
            stato="pending",
        )
        
        # Calcola alert_programmata_il (verrà fatto automaticamente dal save, ma lo impostiamo qui)
        if occorrenza.alert_programmata_il:
            alert.alert_programmata_il = occorrenza.alert_programmata_il
        
        if occorrenza.alert_inviata_il:
            alert.alert_inviata_il = occorrenza.alert_inviata_il
            alert.stato = "sent"
        
        alerts_to_create.append(alert)
    
    # Creazione in blocco per performance
    if alerts_to_create:
        ScadenzaAlert.objects.bulk_create(alerts_to_create, batch_size=500)
        print(f"✓ Migrati {len(alerts_to_create)} alert al nuovo modello ScadenzaAlert")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: non facciamo nulla perché non vogliamo perdere i nuovi alert.
    Gli alert multipli non possono essere rimappati a un singolo offset_alert_minuti.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0005_scadenza_data_scadenza_scadenza_num_occorrenze_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_alerts_to_new_model, reverse_migration),
    ]
