# Generated by Django 5.2.8 on 2025-11-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0006_migrate_alerts_to_new_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scadenza",
            name="stato",
            field=models.CharField(
                choices=[
                    ("bozza", "Bozza"),
                    ("attiva", "Attiva"),
                    ("completata", "Completata"),
                    ("archiviata", "Archiviata"),
                    ("in_scadenza", "In scadenza"),
                    ("scaduta", "Scaduta"),
                ],
                db_index=True,
                default="attiva",
                max_length=20,
            ),
        ),
    ]
