# Generated by Django 5.2.8 on 2025-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0007_alter_scadenza_stato"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodiceTributoF24",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        db_index=True,
                        help_text="Codice identificativo del tributo (es: 1001, 1040, ecc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "sezione",
                    models.CharField(
                        choices=[
                            ("erario", "Erario"),
                            ("inps", "INPS"),
                            ("regioni", "Regioni"),
                            ("altri", "Altri Enti Previdenziali"),
                            ("imu", "IMU e altri tributi locali"),
                            ("inail", "INAIL"),
                            ("accise", "Accise"),
                        ],
                        db_index=True,
                        help_text="Sezione del modello F24",
                        max_length=20,
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        help_text="Descrizione completa del tributo", max_length=500
                    ),
                ),
                (
                    "causale",
                    models.CharField(
                        blank=True,
                        help_text="Causale/sigla del tributo",
                        max_length=100,
                    ),
                ),
                (
                    "periodicita",
                    models.CharField(
                        blank=True,
                        help_text="Periodicità del versamento (mensile, trimestrale, annuale, ecc.)",
                        max_length=50,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Note e informazioni aggiuntive sul tributo",
                    ),
                ),
                (
                    "attivo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica se il codice tributo è ancora utilizzabile",
                    ),
                ),
                (
                    "data_inizio_validita",
                    models.DateField(
                        blank=True,
                        help_text="Data da cui il codice è valido",
                        null=True,
                    ),
                ),
                (
                    "data_fine_validita",
                    models.DateField(
                        blank=True,
                        help_text="Data fino a cui il codice è valido (se applicabile)",
                        null=True,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Codice Tributo F24",
                "verbose_name_plural": "Codici Tributo F24",
                "ordering": ["sezione", "codice"],
                "indexes": [
                    models.Index(
                        fields=["codice", "attivo"],
                        name="scadenze_co_codice_9eec5e_idx",
                    ),
                    models.Index(
                        fields=["sezione", "attivo"],
                        name="scadenze_co_sezione_8bf4b9_idx",
                    ),
                ],
            },
        ),
    ]
