# Generated by Django 5.2.8 on 2026-02-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0008_codicetributof24"),
    ]

    operations = [
        # Fix cascade delete per ScadenzaNotificaLog.occorrenza
        migrations.RunSQL(
            sql="""
                ALTER TABLE scadenze_scadenzanotificalog
                DROP CONSTRAINT IF EXISTS scadenze_scadenzanot_occorrenza_id_83672f59_fk_scadenze_;
                
                ALTER TABLE scadenze_scadenzanotificalog
                ADD CONSTRAINT scadenze_scadenzanot_occorrenza_id_83672f59_fk_scadenze_
                FOREIGN KEY (occorrenza_id)
                REFERENCES scadenze_scadenzaoccorrenza(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE scadenze_scadenzanotificalog
                DROP CONSTRAINT IF EXISTS scadenze_scadenzanot_occorrenza_id_83672f59_fk_scadenze_;
                
                ALTER TABLE scadenze_scadenzanotificalog
                ADD CONSTRAINT scadenze_scadenzanot_occorrenza_id_83672f59_fk_scadenze_
                FOREIGN KEY (occorrenza_id)
                REFERENCES scadenze_scadenzaoccorrenza(id)
                ON DELETE CASCADE;
            """,
        ),
        # Fix cascade delete per ScadenzaAlert.occorrenza
        migrations.RunSQL(
            sql="""
                ALTER TABLE scadenze_scadenzaalert
                DROP CONSTRAINT IF EXISTS scadenze_scadenzaale_occorrenza_id_f8a3c4d2_fk_scadenze_;
                
                ALTER TABLE scadenze_scadenzaalert
                ADD CONSTRAINT scadenze_scadenzaale_occorrenza_id_f8a3c4d2_fk_scadenze_
                FOREIGN KEY (occorrenza_id)
                REFERENCES scadenze_scadenzaoccorrenza(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE scadenze_scadenzaalert
                DROP CONSTRAINT IF EXISTS scadenze_scadenzaale_occorrenza_id_f8a3c4d2_fk_scadenze_;
                
                ALTER TABLE scadenze_scadenzaalert
                ADD CONSTRAINT scadenze_scadenzaale_occorrenza_id_f8a3c4d2_fk_scadenze_
                FOREIGN KEY (occorrenza_id)
                REFERENCES scadenze_scadenzaoccorrenza(id)
                ON DELETE CASCADE;
            """,
        ),
        # Fix cascade delete per ScadenzaWebhookPayload.occorrenza
        migrations.RunSQL(
            sql="""
                ALTER TABLE scadenze_scadenzawebhookpayload
                DROP CONSTRAINT IF EXISTS scadenze_scadenzaweb_occorrenza_id_9b7e2f1a_fk_scadenze_;
                
                ALTER TABLE scadenze_scadenzawebhookpayload
                ADD CONSTRAINT scadenze_scadenzaweb_occorrenza_id_9b7e2f1a_fk_scadenze_
                FOREIGN KEY (occorrenza_id)
                REFERENCES scadenze_scadenzaoccorrenza(id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE scadenze_scadenzawebhookpayload
                DROP CONSTRAINT IF EXISTS scadenze_scadenzaweb_occorrenza_id_9b7e2f1a_fk_scadenze_;
                
                ALTER TABLE scadenze_scadenzawebhookpayload
                ADD CONSTRAINT scadenze_scadenzaweb_occorrenza_id_9b7e2f1a_fk_scadenze_
                FOREIGN KEY (occorrenza_id)
                REFERENCES scadenze_scadenzaoccorrenza(id)
                ON DELETE CASCADE;
            """,
        ),
    ]
