# Generated by Django 5.2.8 on 2026-02-03 09:37

from django.db import migrations


def cleanup_orphaned_records(apps, schema_editor):
    """
    Pulisce record orfani che potrebbero essersi creati prima della fix
    dei constraint CASCADE deferribili.
    """
    ScadenzaNotificaLog = apps.get_model('scadenze', 'ScadenzaNotificaLog')
    ScadenzaAlert = apps.get_model('scadenze', 'ScadenzaAlert')
    ScadenzaWebhookPayload = apps.get_model('scadenze', 'ScadenzaWebhookPayload')
    ScadenzaOccorrenza = apps.get_model('scadenze', 'ScadenzaOccorrenza')
    
    # Ottieni tutti gli ID validi di occorrenze
    valid_occorrenza_ids = set(ScadenzaOccorrenza.objects.values_list('id', flat=True))
    
    # Elimina log orfani
    orphaned_logs = ScadenzaNotificaLog.objects.exclude(occorrenza_id__in=valid_occorrenza_ids)
    log_count = orphaned_logs.count()
    if log_count > 0:
        orphaned_logs.delete()
        print(f"  → Eliminati {log_count} ScadenzaNotificaLog orfani")
    
    # Elimina alert orfani
    orphaned_alerts = ScadenzaAlert.objects.exclude(occorrenza_id__in=valid_occorrenza_ids)
    alert_count = orphaned_alerts.count()
    if alert_count > 0:
        orphaned_alerts.delete()
        print(f"  → Eliminati {alert_count} ScadenzaAlert orfani")
    
    # Elimina webhook orfani
    orphaned_webhooks = ScadenzaWebhookPayload.objects.exclude(occorrenza_id__in=valid_occorrenza_ids)
    webhook_count = orphaned_webhooks.count()
    if webhook_count > 0:
        orphaned_webhooks.delete()
        print(f"  → Eliminati {webhook_count} ScadenzaWebhookPayload orfani")
    
    if log_count == 0 and alert_count == 0 and webhook_count == 0:
        print("  ✓ Nessun record orfano trovato")


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0009_fix_cascade_delete_constraints"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_records,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
