# Generated by Django 4.2.16 on 2026-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0011_scadenzaalert_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scadenzaalert",
            name="metodo_alert",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "Webhook"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                ],
                db_index=True,
                default="email",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scadenzanotificalog",
            name="evento",
            field=models.CharField(
                choices=[
                    ("calendar_sync", "Sincronizzazione calendario"),
                    ("alert_scheduled", "Alert programmato"),
                    ("alert_sent", "Alert inviato"),
                    ("webhook_error", "Errore webhook"),
                    ("email_error", "Errore email"),
                    ("whatsapp_error", "Errore WhatsApp"),
                    ("telegram_error", "Errore Telegram"),
                    ("bulk_generation", "Generazione massiva"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="scadenzaoccorrenza",
            name="metodo_alert",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "Webhook"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                ],
                db_index=True,
                default="email",
                max_length=20,
            ),
        ),
    ]
