# Generated by Django 4.2.16 on 2026-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scadenze", "0012_telegram_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="scadenza",
            name="posticipa_festivi",
            field=models.BooleanField(
                default=True,
                help_text="Se un'occorrenza generata cade in un giorno festivo italiano o nel weekend, posticipala automaticamente al primo giorno feriale utile.",
            ),
        ),
    ]
