"""
Django settings for mygest project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.core.files.storage import FileSystemStorage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2c^)jnpbhbx311i--n@px58iczkm90-1^zus@4^z)x^x#e4a-y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'graphene_django',
    'anagrafiche',
    'archivio_fisico',
    'documenti',
    'fascicoli',
    'pratiche',
    'scadenze',
    'stampe',
    'titolario',
    "django_addanother",
    "protocollo",
    "crispy_forms",
    "crispy_bootstrap5",
    "comunicazioni",
    "whatsapp",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mygest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # aggiornato
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "mygest.context_processors.app_name",
    "mygest.context_processors.breadcrumbs",
]

WSGI_APPLICATION = 'mygest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mygest',
        'USER': 'mygest_user',
        'PASSWORD': 'ScegliUnaPasswordSicura',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Email configuration
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtps.aruba.it")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() in {"1", "true", "yes", "on"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "true").lower() in {"1", "true", "yes", "on"}
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise RuntimeError("EMAIL_USE_TLS e EMAIL_USE_SSL non possono essere entrambi attivi.")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "sandrochimenti@secamonline.it")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "001CambiamI@")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "info@secamonline.it")
_default_failover = "true" if DEBUG else "false"
EMAIL_FAILOVER_TO_CONSOLE = os.getenv("EMAIL_FAILOVER_TO_CONSOLE", _default_failover).lower() in {"1", "true", "yes", "on"}
EMAIL_IMAP_HOST = os.getenv("EMAIL_IMAP_HOST", "imaps.aruba.it")
EMAIL_IMAP_PORT = int(os.getenv("EMAIL_IMAP_PORT", "993"))
EMAIL_IMAP_USER = os.getenv("EMAIL_IMAP_USER", EMAIL_HOST_USER)
EMAIL_IMAP_PASSWORD = os.getenv("EMAIL_IMAP_PASSWORD", EMAIL_HOST_PASSWORD)
EMAIL_IMAP_SENT_FOLDER = os.getenv("EMAIL_IMAP_SENT_FOLDER", "Inviati")
_imap_sent_folders = os.getenv("EMAIL_IMAP_SENT_FOLDERS", "")
if _imap_sent_folders:
    EMAIL_IMAP_SENT_FOLDERS = [f.strip() for f in _imap_sent_folders.split(",") if f.strip()]
else:
    EMAIL_IMAP_SENT_FOLDERS = []
EMAIL_IMAP_TIMEOUT = int(os.getenv("EMAIL_IMAP_TIMEOUT", os.getenv("EMAIL_TIMEOUT", "30")))

if any(arg.startswith("test") or os.path.basename(arg).startswith("pytest") for arg in sys.argv):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# NAS / Archivio
ARCHIVIO_BASE_PATH = os.getenv("ARCHIVIO_BASE_PATH", "/mnt/archivio")
NAS_STORAGE = FileSystemStorage(location=ARCHIVIO_BASE_PATH)

# Importazioni
IMPORTAZIONI_SOURCE_DIRS = [
    "/home/sandro/documenti",
    "/mnt/archivio/importazioni",
]

# Auth redirects (aggiorna le URL se non esistono)
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/classificazione/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Etichette / stampa
DYMO_PRINTER_NAME = "DYMO_LabelWriter_450"
ETICHETTE_SERVER_PRINT = False
ETICHETTE_MARGIN_MM = 10.0

# Documenti
DOCUMENTI_FILE_PATTERN_DEFAULT = "{tipo.codice}_{id}_{attr:repertorio_atto|REPNA}_{data_documento:%Y%m%d}_{slug:descrizione}.pdf"
DOCUMENTI_RENAME_ONLY_NEW = True
DOCUMENTI_FILENAME_MAX_LEN = 140
DOCUMENTI_PATTERN_ENABLE_UNIQUE = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",)
CRISPY_TEMPLATE_PACK = "bootstrap5"


ARCHIVIO_FISICO_UNITA_SCARICO_ID = 28  # sostituisci con l'ID reale

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

GRAPHENE = {
    "SCHEMA": "mygest.schema.schema",
}

# Google Calendar integration to sync scadenze
GOOGLE_CALENDAR_CREDENTIALS_FILE = os.getenv("GOOGLE_CALENDAR_CREDENTIALS_FILE", "/home/sandro/mygest/google_credentials.json")
GOOGLE_CALENDAR_DEFAULT_ID = os.getenv("GOOGLE_CALENDAR_DEFAULT_ID", "9a9573ab346e1f5710ffaed4af6dc336f70c7690267a918326134fb9e77a8b20@group.calendar.google.com")

# WhatsApp Cloud API integration
WHATSAPP_CLOUD_API_VERSION = os.getenv("WHATSAPP_CLOUD_API_VERSION", "v20.0")
WHATSAPP_CLOUD_BASE_URL = os.getenv("WHATSAPP_CLOUD_BASE_URL", "https://graph.facebook.com")
WHATSAPP_CLOUD_PHONE_NUMBER_ID = os.getenv("WHATSAPP_CLOUD_PHONE_NUMBER_ID", "")
WHATSAPP_CLOUD_BUSINESS_ACCOUNT_ID = os.getenv("WHATSAPP_CLOUD_BUSINESS_ACCOUNT_ID", "")
WHATSAPP_CLOUD_ACCESS_TOKEN = os.getenv("WHATSAPP_CLOUD_ACCESS_TOKEN", "")
WHATSAPP_CLOUD_VERIFY_TOKEN = os.getenv("WHATSAPP_CLOUD_VERIFY_TOKEN", "")
WHATSAPP_CLOUD_APP_SECRET = os.getenv("WHATSAPP_CLOUD_APP_SECRET", "")
WHATSAPP_CLOUD_TIMEOUT = int(os.getenv("WHATSAPP_CLOUD_TIMEOUT", "10"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "protocollo": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "protocollazione_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "protocollo",
            "filename": str(LOG_DIR / "protocollazione.log"),
            "when": "midnight",
            "backupCount": 14,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "documenti.protocollo": {
            "handlers": ["protocollazione_file"],
            "level": "INFO",
            "propagate": False,
        },
        "documenti.protocollazione": {
            "handlers": ["protocollazione_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}