"""
Django settings for mygest project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.core.files.storage import FileSystemStorage
import environ

# Initialize environment variables
env = environ.Env(
    # Set casting and default values
    DEBUG=(bool, False),
    SECRET_KEY=(str, 'django-insecure-2c^)jnpbhbx311i--n@px58iczkm90-1^zus@4^z)x^x#e4a-y'),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file if it exists
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Parse ALLOWED_HOSTS from environment
ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # Token Authentication per Agent Desktop
    'rest_framework_simplejwt',  # JWT Authentication
    'corsheaders',  # CORS Headers
    'django_filters',  # Django Filter per API
    'graphene_django',
    'compressor',  # Django Compressor per ottimizzazione statica
    'anagrafiche',
    'archivio_fisico',
    'documenti',
    'fascicoli',
    'pratiche',
    'scadenze',
    'stampe',
    'titolario',
    "django_addanother",
    "protocollo",
    "crispy_forms",
    "crispy_bootstrap5",
    "comunicazioni",
    "whatsapp",
    "ai_classifier",  # AI Classificatore Documenti
]

# Aggiungi Debug Toolbar solo in sviluppo
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - Must be at top
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve file statici compressi
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Aggiungi Debug Toolbar middleware solo in sviluppo
if DEBUG:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1', 'localhost']

ROOT_URLCONF = 'mygest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # aggiornato
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "mygest.context_processors.app_name",
    "mygest.context_processors.breadcrumbs",
]

WSGI_APPLICATION = 'mygest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'dj_db_conn_pool.backends.postgresql',  # Connection pooling
        'NAME': 'mygest',
        'USER': 'mygest_user',
        'PASSWORD': 'ScegliUnaPasswordSicura',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'POOL_OPTIONS': {
            'POOL_SIZE': 10,
            'MAX_OVERFLOW': 20,
            'RECYCLE': 3600,  # Ricicla connessioni dopo 1 ora
            'PRE_PING': True,  # Verifica connessioni prima dell'uso
        }
    }
}


# ====================================
# CACHING CONFIGURATION
# ====================================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'PARSER_CLASS': 'redis.connection.HiredisParser',
        },
        'KEY_PREFIX': 'mygest',
        'TIMEOUT': 300,  # 5 minuti default
    },
    # Cache separata per sessioni
    'session': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/2'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'mygest_session',
        'TIMEOUT': 86400,  # 24 ore per sessioni
    },
}

# Usa Redis per le sessioni
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'session'


# Email configuration
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtps.aruba.it")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() in {"1", "true", "yes", "on"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "true").lower() in {"1", "true", "yes", "on"}
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise RuntimeError("EMAIL_USE_TLS e EMAIL_USE_SSL non possono essere entrambi attivi.")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "sandrochimenti@secamonline.it")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "001CambiamI@")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "info@secamonline.it")
_default_failover = "true" if DEBUG else "false"
EMAIL_FAILOVER_TO_CONSOLE = os.getenv("EMAIL_FAILOVER_TO_CONSOLE", _default_failover).lower() in {"1", "true", "yes", "on"}
EMAIL_IMAP_HOST = os.getenv("EMAIL_IMAP_HOST", "imaps.aruba.it")
EMAIL_IMAP_PORT = int(os.getenv("EMAIL_IMAP_PORT", "993"))
EMAIL_IMAP_USER = os.getenv("EMAIL_IMAP_USER", EMAIL_HOST_USER)
EMAIL_IMAP_PASSWORD = os.getenv("EMAIL_IMAP_PASSWORD", EMAIL_HOST_PASSWORD)
EMAIL_IMAP_SENT_FOLDER = os.getenv("EMAIL_IMAP_SENT_FOLDER", "Inviati")
_imap_sent_folders = os.getenv("EMAIL_IMAP_SENT_FOLDERS", "")
if _imap_sent_folders:
    EMAIL_IMAP_SENT_FOLDERS = [f.strip() for f in _imap_sent_folders.split(",") if f.strip()]
else:
    EMAIL_IMAP_SENT_FOLDERS = []
EMAIL_IMAP_TIMEOUT = int(os.getenv("EMAIL_IMAP_TIMEOUT", os.getenv("EMAIL_TIMEOUT", "30")))

if any(arg.startswith("test") or os.path.basename(arg).startswith("pytest") for arg in sys.argv):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ====================================
# STATICFILES & COMPRESSION
# ====================================
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',  # Django Compressor
]

# Whitenoise con compressione Brotli
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Django Compressor settings
COMPRESS_ENABLED = not DEBUG  # Comprimi in produzione
COMPRESS_OFFLINE = not DEBUG  # Pre-compressione in produzione
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]

# Archivio / Storage configurazione
# Ambiente di sviluppo (WSL): /mnt/archivio (montaggio NAS)
# Ambiente produzione (VPS): /srv/mygest/archivio
ARCHIVIO_BASE_PATH = os.getenv("ARCHIVIO_BASE_PATH", "/mnt/archivio")

# Media URL per servire i file dell'archivio
MEDIA_URL = '/archivio/'
# MEDIA_ROOT non utilizzato - tutti i file vanno in ARCHIVIO_BASE_PATH
# Manteniamo la definizione per compatibilità con eventuali app di terze parti
MEDIA_ROOT = ARCHIVIO_BASE_PATH

# Storage personalizzato per NAS
NAS_STORAGE = FileSystemStorage(location=ARCHIVIO_BASE_PATH)

# Importazioni
IMPORTAZIONI_SOURCE_DIRS = [
    "/home/sandro/documenti",
    "/mnt/archivio/importazioni",
]

# Auth redirects (aggiorna le URL se non esistono)
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/classificazione/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Etichette / stampa
DYMO_PRINTER_NAME = "DYMO_LabelWriter_450"
ETICHETTE_SERVER_PRINT = False
ETICHETTE_MARGIN_MM = 10.0

# Documenti
DOCUMENTI_FILE_PATTERN_DEFAULT = "{tipo.codice}_{id}_{attr:repertorio_atto|REPNA}_{data_documento:%Y%m%d}_{slug:descrizione}.pdf"
DOCUMENTI_RENAME_ONLY_NEW = True
DOCUMENTI_FILENAME_MAX_LEN = 140
DOCUMENTI_PATTERN_ENABLE_UNIQUE = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",)
CRISPY_TEMPLATE_PACK = "bootstrap5"


ARCHIVIO_FISICO_UNITA_SCARICO_ID = 28  # sostituisci con l'ID reale

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT First
        "rest_framework.authentication.TokenAuthentication",  # Token per Agent Desktop
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Throttling disabilitato (richiede Redis)
    # "DEFAULT_THROTTLE_CLASSES": [
    #     "rest_framework.throttling.AnonRateThrottle",
    #     "rest_framework.throttling.UserRateThrottle",
    # ],
    # "DEFAULT_THROTTLE_RATES": {
    #     "anon": "100/hour",
    #     "user": "1000/hour",
    # },
}

GRAPHENE = {
    "SCHEMA": "mygest.schema.schema",
}

# Google Calendar integration to sync scadenze
GOOGLE_CALENDAR_CREDENTIALS_FILE = os.getenv("GOOGLE_CALENDAR_CREDENTIALS_FILE", "/home/sandro/mygest/google_credentials.json")
GOOGLE_CALENDAR_DEFAULT_ID = os.getenv("GOOGLE_CALENDAR_DEFAULT_ID", "9a9573ab346e1f5710ffaed4af6dc336f70c7690267a918326134fb9e77a8b20@group.calendar.google.com")

# WhatsApp Cloud API integration
WHATSAPP_CLOUD_API_VERSION = os.getenv("WHATSAPP_CLOUD_API_VERSION", "v20.0")
WHATSAPP_CLOUD_BASE_URL = os.getenv("WHATSAPP_CLOUD_BASE_URL", "https://graph.facebook.com")
WHATSAPP_CLOUD_PHONE_NUMBER_ID = os.getenv("WHATSAPP_CLOUD_PHONE_NUMBER_ID", "")
WHATSAPP_CLOUD_BUSINESS_ACCOUNT_ID = os.getenv("WHATSAPP_CLOUD_BUSINESS_ACCOUNT_ID", "")
WHATSAPP_CLOUD_ACCESS_TOKEN = os.getenv("WHATSAPP_CLOUD_ACCESS_TOKEN", "")
WHATSAPP_CLOUD_VERIFY_TOKEN = os.getenv("WHATSAPP_CLOUD_VERIFY_TOKEN", "")
WHATSAPP_CLOUD_APP_SECRET = os.getenv("WHATSAPP_CLOUD_APP_SECRET", "")
WHATSAPP_CLOUD_TIMEOUT = int(os.getenv("WHATSAPP_CLOUD_TIMEOUT", "10"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "protocollo": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "protocollazione_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "protocollo",
            "filename": str(LOG_DIR / "protocollazione.log"),
            "when": "midnight",
            "backupCount": 14,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "documenti.protocollo": {
            "handlers": ["protocollazione_file"],
            "level": "INFO",
            "propagate": False,
        },
        "documenti.protocollazione": {
            "handlers": ["protocollazione_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ====================================
# CORS CONFIGURATION (for React SPA)
# ====================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev server
    "http://localhost:3000",  # Alternative port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins (necessario per POST da frontend)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
]

# CSRF Cookie Settings per SPA
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_HTTPONLY = False  # Permette al JavaScript di leggere il cookie
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SECURE = False  # False in development, True in production con HTTPS

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# ====================================
# JWT AUTHENTICATION CONFIGURATION
# ====================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # Disabilitato: richiede Redis
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}


# ====================================
# AI CLASSIFIER SETTINGS
# ====================================
AI_CLASSIFIER = {
    'DEFAULT_LLM_PROVIDER': 'openai',
    'OPENAI_MODEL': 'gpt-4o-mini',
    'OPENAI_API_KEY': os.getenv('OPENAI_API_KEY', ''),  # Da variabile ambiente
    'LLM_TEMPERATURE': 0.1,  # Bassa per classificazione deterministica
    'LLM_MAX_TOKENS': 500,
    'CONFIDENCE_THRESHOLD': 0.7,
    'MAX_FILE_SIZE_MB': 50,
    'ALLOWED_EXTENSIONS': ['.pdf', '.jpg', '.jpeg', '.png', '.tiff', '.docx'],
}


# ====================================
# IMPORT SETTINGS LOCALI
# ====================================
# Importa impostazioni locali/produzione se esistono
# Questo file NON è su git e deve essere creato manualmente in ogni ambiente
try:
    from .settings_local import *  # noqa: F401, F403
    print("✓ Settings locali caricati da settings_local.py")
except ImportError:
    print("⚠ settings_local.py non trovato - usando configurazione di default")
    print("  Copia settings_local.py.example -> settings_local.py e personalizza")
    pass