# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitaFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.SlugField(help_text="Codice univoco per il padre")),
                ("nome", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ufficio", "Ufficio"),
                            ("stanza", "Stanza"),
                            ("scaffale", "Scaffale"),
                            ("mobile", "Mobile"),
                            ("anta", "Anta"),
                            ("ripiano", "Ripiano"),
                            ("contenitore", "Contenitore"),
                            ("cartellina", "Cartellina"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                (
                    "full_path",
                    models.CharField(blank=True, editable=False, max_length=500),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="figli",
                        to="archivio_fisico.unitafisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unità fisica",
                "verbose_name_plural": "Unità fisiche",
                "ordering": ["parent__id", "ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="CollocazioneFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("attiva", models.BooleanField(default=True)),
                ("dal", models.DateField(default=django.utils.timezone.now)),
                ("al", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=250)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collocazione fisica",
                "verbose_name_plural": "Collocazioni fisiche",
                "ordering": ["-attiva", "-dal", "-id"],
            },
        ),
    ]
