# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archivio_fisico", "0001_initial"),
        ("documenti", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collocazionefisica",
            name="documento",
            field=models.ForeignKey(
                blank=True,
                help_text="Se valorizzato, la collocazione è riferita a un Documento specifico.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collocazioni_fisiche",
                to="documenti.documento",
            ),
        ),
        migrations.AddField(
            model_name="collocazionefisica",
            name="unita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collocazioni",
                to="archivio_fisico.unitafisica",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitafisica",
            constraint=models.UniqueConstraint(
                fields=("parent", "codice"), name="uniq_unita_by_parent_codice"
            ),
        ),
        migrations.AddIndex(
            model_name="collocazionefisica",
            index=models.Index(
                fields=["content_type", "object_id", "attiva"],
                name="archivio_fi_content_d9b70f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collocazionefisica",
            index=models.Index(
                fields=["documento", "attiva"], name="archivio_fi_documen_51fd74_idx"
            ),
        ),
    ]
