# Generated by Django 4.2.16 on 2025-10-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitafisica",
            name="archivio_fisso",
            field=models.BooleanField(
                default=False, help_text="Flag sì/no: unità destinata ad archivio fisso"
            ),
        ),
    ]
