# Generated by Django 4.2.16 on 2025-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0003_unitafisica_archivio_fisso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ubicazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=50, unique=True)),
                ("descrizione", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Ubicazione",
                "verbose_name_plural": "Ubicazioni",
                "ordering": ["codice"],
            },
        ),
    ]
