# Generated by Django 4.2.16 on 2025-10-29 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0002_alter_protocollocounter_unique_together_and_more"),
        ("fascicoli", "0006_alter_fascicolo_cliente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafiche", "0004_anagrafica_codice"),
        ("protocollo", "0004_movimentoprotocollo_fascicolo_and_more"),
        ("archivio_fisico", "0004_ubicazione"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperazioneArchivio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operazione",
                    models.CharField(
                        choices=[
                            ("entrata", "Entrata"),
                            ("uscita", "Uscita"),
                            ("interna", "Movimento interno"),
                        ],
                        max_length=10,
                    ),
                ),
                ("data_ora", models.DateTimeField(auto_now_add=True)),
                ("stato_precedente", models.CharField(blank=True, max_length=30)),
                ("stato_successivo", models.CharField(blank=True, max_length=30)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documenti.documento",
                    ),
                ),
                (
                    "fascicolo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fascicoli.fascicolo",
                    ),
                ),
                (
                    "movimento_protocollo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Movimento di protocollo collegato, se la movimentazione coincide con una consegna/ritiro da/verso l'esterno.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operazioni_archivio",
                        to="protocollo.movimentoprotocollo",
                    ),
                ),
                (
                    "operazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="archivio_fisico.operazionearchivio",
                    ),
                ),
                (
                    "referente_esterno",
                    models.ForeignKey(
                        blank=True,
                        help_text="Persona esterna coinvolta (mittente/destinatario), opzionale per movimenti interni.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operazioni_archivio_esterni",
                        to="anagrafiche.anagrafica",
                    ),
                ),
                (
                    "referente_interno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operazioni_archivio_interni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unita_fisica_destinazione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unità fisica di arrivo (necessaria per entrata/interna)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operazioni_entrata",
                        to="archivio_fisico.unitafisica",
                    ),
                ),
                (
                    "unita_fisica_sorgente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unità fisica di partenza (necessaria per uscita/interna)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operazioni_uscita",
                        to="archivio_fisico.unitafisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riga operazione archivio fisico",
                "verbose_name_plural": "Righe operazioni archivio fisico",
            },
        ),
    ]
