# Generated by Django 4.2.16 on 2025-10-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fascicoli", "0006_alter_fascicolo_cliente"),
        ("documenti", "0002_alter_protocollocounter_unique_together_and_more"),
        ("archivio_fisico", "0005_operazionearchivio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operazionearchivio",
            options={
                "ordering": ["-data_ora"],
                "verbose_name": "Operazione archivio fisico",
                "verbose_name_plural": "Operazioni archivio fisico",
            },
        ),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="fascicolo",
        ),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="operazione",
        ),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="stato_precedente",
        ),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="stato_successivo",
        ),
        migrations.AlterField(
            model_name="operazionearchivio",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="RigaOperazioneArchivio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stato_precedente", models.CharField(blank=True, max_length=30)),
                ("stato_successivo", models.CharField(blank=True, max_length=30)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documenti.documento",
                    ),
                ),
                (
                    "fascicolo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fascicoli.fascicolo",
                    ),
                ),
                (
                    "operazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="archivio_fisico.operazionearchivio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riga operazione archivio fisico",
                "verbose_name_plural": "Righe operazioni archivio fisico",
            },
        ),
    ]
