# Generated by Django 4.2.16 on 2025-11-04 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0008_unitafisica_codice_progressivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerbaleConsegnaTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "file_template",
                    models.FileField(
                        max_length=500,
                        upload_to="archivio_fisico/verbali/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["docx"])
                        ],
                    ),
                ),
                (
                    "filename_pattern",
                    models.CharField(
                        default="verbale_{operazione_id}_{timestamp:%Y%m%d_%H%M}.docx",
                        help_text="Pattern per il nome del file generato. Token disponibili: {operazione_id}, {operazione_tipo}, {operazione_tipo_display}, {timestamp:%Y%m%d}, {template_slug}. Usa sintassi Python format.",
                        max_length=200,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Se attivo, diventa il template proposto di default per il download.",
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template verbale di consegna",
                "verbose_name_plural": "Template verbali di consegna",
                "ordering": ["nome"],
            },
        ),
    ]
