# Generated by Django 4.2.16 on 2025-11-05 15:13

from django.db import migrations, models
import django.db.models.deletion


def copy_movimenti_to_righe(apps, schema_editor):
    Operazione = apps.get_model('archivio_fisico', 'OperazioneArchivio')
    Riga = apps.get_model('archivio_fisico', 'RigaOperazioneArchivio')

    for operazione in Operazione.objects.exclude(movimento_protocollo__isnull=True).iterator():
        movimento_id = operazione.movimento_protocollo_id
        if not movimento_id:
            continue
        Riga.objects.filter(
            operazione=operazione,
            movimento_protocollo__isnull=True,
        ).update(movimento_protocollo_id=movimento_id)


class Migration(migrations.Migration):

    dependencies = [
        ('protocollo', '0004_movimentoprotocollo_fascicolo_and_more'),
        ('archivio_fisico', '0009_verbaleconsegnatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaoperazionearchivio',
            name='movimento_protocollo',
            field=models.ForeignKey(blank=True, help_text='Movimento di protocollo collegato specifico per la riga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_operazione_archivio', to='protocollo.movimentoprotocollo'),
        ),
        migrations.RunPython(
            code=copy_movimenti_to_righe,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='operazionearchivio',
            name='movimento_protocollo',
        ),
    ]
