# Generated by Django 4.2.16 on 2025-11-06 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivio_fisico', '0010_remove_operazionearchivio_movimento_protocollo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operazionearchivio',
            name='verbale_scan',
            field=models.FileField(blank=True, help_text='Facoltativo: carica la scansione del verbale firmato.', max_length=500, null=True, upload_to='archivio/operazioni', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'tif', 'tiff'])]),
        ),
    ]
