# Generated by Django 4.2.16 on 2025-11-06 12:02

from django.db import migrations, models
import django.db.models.deletion


def copy_units_to_rows(apps, schema_editor):
    Operazione = apps.get_model("archivio_fisico", "OperazioneArchivio")
    Riga = apps.get_model("archivio_fisico", "RigaOperazioneArchivio")
    righe = Riga.objects.select_related("operazione").all()
    for riga in righe:
        operazione = getattr(riga, "operazione", None)
        if operazione is None:
            continue
        update_fields = []
        if (
            riga.unita_fisica_sorgente_id is None
            and getattr(operazione, "unita_fisica_sorgente_id", None) is not None
        ):
            riga.unita_fisica_sorgente_id = operazione.unita_fisica_sorgente_id
            update_fields.append("unita_fisica_sorgente")
        if (
            riga.unita_fisica_destinazione_id is None
            and getattr(operazione, "unita_fisica_destinazione_id", None) is not None
        ):
            riga.unita_fisica_destinazione_id = operazione.unita_fisica_destinazione_id
            update_fields.append("unita_fisica_destinazione")
        if update_fields:
            riga.save(update_fields=update_fields)


def copy_units_to_operations(apps, schema_editor):
    Operazione = apps.get_model("archivio_fisico", "OperazioneArchivio")
    Riga = apps.get_model("archivio_fisico", "RigaOperazioneArchivio")
    operazioni = Operazione.objects.all()
    for operazione in operazioni:
        righe = list(operazione.righe.all())
        if not righe:
            continue
        sorgente = next((r.unita_fisica_sorgente_id for r in righe if r.unita_fisica_sorgente_id), None)
        destinazione = next((r.unita_fisica_destinazione_id for r in righe if r.unita_fisica_destinazione_id), None)
        update_fields = []
        if sorgente is not None:
            operazione.unita_fisica_sorgente_id = sorgente
            update_fields.append("unita_fisica_sorgente")
        if destinazione is not None:
            operazione.unita_fisica_destinazione_id = destinazione
            update_fields.append("unita_fisica_destinazione")
        if update_fields:
            operazione.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0011_operazionearchivio_verbale_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="rigaoperazionearchivio",
            name="unita_fisica_destinazione",
            field=models.ForeignKey(
                blank=True,
                help_text="Unità di arrivo della movimentazione per questa riga.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="righe_destinazione",
                to="archivio_fisico.unitafisica",
            ),
        ),
        migrations.AddField(
            model_name="rigaoperazionearchivio",
            name="unita_fisica_sorgente",
            field=models.ForeignKey(
                blank=True,
                help_text="Unità di partenza della movimentazione per questa riga.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="righe_sorgente",
                to="archivio_fisico.unitafisica",
            ),
        ),
        migrations.RunPython(copy_units_to_rows, copy_units_to_operations),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="unita_fisica_destinazione",
        ),
        migrations.RemoveField(
            model_name="operazionearchivio",
            name="unita_fisica_sorgente",
        ),
    ]
