# Generated by Django 4.2.16 on 2025-11-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0013_create_vw_catalogo_unitafisica"),
    ]

    operations = [
        migrations.CreateModel(
            name="VwCatalogoUnitafisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.TextField(blank=True, null=True)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("entity_codice", models.CharField(blank=True, null=True)),
                ("entity_descrizione", models.CharField(blank=True, null=True)),
                ("movimento_id", models.BigIntegerField(blank=True, null=True)),
                ("anno", models.IntegerField(blank=True, null=True)),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("direzione", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "ubicazione_codice",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "ubicazione_descrizione",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
            ],
            options={
                "db_table": "vw_catalogo_unitafisica",
                "managed": False,
            },
        ),
    ]
