# Generated by Django 4.2.16 on 2025-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0015_update_catalogounitafisica_contenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoUnitaFisica",
            fields=[
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.BigIntegerField()),
                ("entity_codice", models.CharField(max_length=120)),
                ("entity_descrizione", models.CharField(max_length=255)),
                (
                    "movimento_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("movimento_anno", models.IntegerField()),
                ("movimento_numero", models.IntegerField()),
                ("movimento_direzione", models.CharField(max_length=3)),
                ("movimento_data", models.DateTimeField()),
                ("destinatario", models.CharField(blank=True, max_length=255)),
                ("ubicazione_id", models.BigIntegerField()),
                ("ubicazione_codice", models.CharField(max_length=60)),
                ("ubicazione_nome", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "vw_catalogo_unitafisica",
                "ordering": ["movimento_data", "movimento_id"],
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="VwCatalogoUnitafisica",
        ),
    ]
