# Generated by Django 5.2.8 on 2025-11-20 16:54

import django.core.validators
import mygest.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0018_create_vw_archivio_fisico_lista_stampa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operazionearchivio",
            name="verbale_scan",
            field=models.FileField(
                blank=True,
                help_text="Facoltativo: carica la scansione del verbale firmato.",
                max_length=500,
                null=True,
                storage=mygest.storages.NASPathStorage(),
                upload_to="archivio_fisico/operazioni",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "tif", "tiff"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="verbaleconsegnatemplate",
            name="file_template",
            field=models.FileField(
                max_length=500,
                storage=mygest.storages.NASPathStorage(),
                upload_to="archivio_fisico/verbali/",
                validators=[django.core.validators.FileExtensionValidator(["docx"])],
            ),
        ),
    ]
