# Generated by Django 5.2.8 on 2026-01-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0009_anagrafica_denominazione_abbreviata"),
        ("archivio_fisico", "0019_alter_operazionearchivio_verbale_scan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitafisica",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente associato all'unità fisica (opzionale)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unita_fisiche",
                to="anagrafiche.cliente",
            ),
        ),
    ]
