# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import documenti.models
import mygest.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafiche", "0001_initial"),
        ("titolario", "0001_initial"),
        ("fascicoli", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributoDefinizione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.SlugField(
                        help_text="Codice univoco per tipo (es. numero_pratica)"
                    ),
                ),
                ("nome", models.CharField(help_text="Etichetta campo", max_length=120)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("string", "Stringa"),
                            ("int", "Intero"),
                            ("decimal", "Decimale"),
                            ("date", "Data"),
                            ("bool", "Booleano"),
                            ("choice", "Scelta"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        help_text="Regex di validazione opzionale",
                        max_length=200,
                    ),
                ),
                (
                    "choices",
                    models.CharField(
                        blank=True,
                        help_text="Lista scelte 'valore|etichetta' separate da virgola",
                        max_length=500,
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("ordine", models.PositiveIntegerField(default=0)),
                (
                    "widget",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rendering del campo: vuoto=default, 'anagrafica'=select Anagrafica",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attributo (definizione)",
                "verbose_name_plural": "Attributi (definizioni)",
                "ordering": ["tipo_documento", "ordine", "codice"],
            },
        ),
        migrations.CreateModel(
            name="DocumentiTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "nome",
                    models.CharField(
                        default="Senza nome",
                        help_text="Nome del tipo di documento (es. Fattura, Contratto, Cedolino, ecc.)",
                        max_length=120,
                    ),
                ),
                (
                    "estensioni_permesse",
                    models.CharField(
                        blank=True,
                        help_text="Estensioni consentite separate da virgola (es. pdf,docx,jpg)",
                        max_length=120,
                    ),
                ),
                (
                    "pattern_codice",
                    models.CharField(
                        default="{CLI}_{TIPO}_{DATA}_{SEQ:03d}",
                        help_text="Pattern per il codice documento: usa {CLI}, {TIPO}, {DATA}, {SEQ}",
                        max_length=120,
                    ),
                ),
                (
                    "nome_file_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Pattern nome file: token {id}, {tipo.codice}, {data_documento:%Y%m%d}, {attr:<codice>}, {slug:descrizione}, {upper:...}/{lower:...}, {if:attr:<codice>:TESTO}/{ifnot:field:<campo>:TESTO}.",
                        max_length=255,
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo documento",
                "verbose_name_plural": "Tipi documento",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(blank=True, max_length=100, unique=True)),
                ("descrizione", models.CharField(max_length=255)),
                ("data_documento", models.DateField(default=django.utils.timezone.now)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("definitivo", "Definitivo"),
                            ("archiviato", "Archiviato"),
                        ],
                        db_index=True,
                        default="bozza",
                        max_length=20,
                    ),
                ),
                (
                    "tracciabile",
                    models.BooleanField(
                        default=True,
                        help_text="Se disattivo, il documento non entra nel flusso di protocollo/movimentazioni (es. carte di lavoro)",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        storage=mygest.storages.NASPathStorage(),
                        upload_to=documenti.models.documento_upload_to,
                    ),
                ),
                (
                    "percorso_archivio",
                    models.CharField(blank=True, editable=False, max_length=500),
                ),
                ("tags", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField(blank=True)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                ("out_aperto", models.BooleanField(db_index=True, default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documenti",
                        to="anagrafiche.anagrafica",
                    ),
                ),
                (
                    "fascicolo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documenti",
                        to="fascicoli.fascicolo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documenti",
                        to="documenti.documentitipo",
                    ),
                ),
                (
                    "titolario_voce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documenti",
                        to="titolario.titolariovoce",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documenti",
                "ordering": ["-data_documento", "codice"],
            },
        ),
        migrations.CreateModel(
            name="Ubicazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=50, unique=True)),
                ("descrizione", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Ubicazione",
                "verbose_name_plural": "Ubicazioni",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documento_counters",
                        to="anagrafiche.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contatore documenti",
                "verbose_name_plural": "Contatori documenti",
            },
        ),
        migrations.CreateModel(
            name="AttributoValore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valore",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "definizione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valori",
                        to="documenti.attributodefinizione",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributi_valori",
                        to="documenti.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attributo (valore)",
                "verbose_name_plural": "Attributi (valori)",
            },
        ),
        migrations.AddField(
            model_name="attributodefinizione",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributi",
                to="documenti.documentitipo",
            ),
        ),
        migrations.CreateModel(
            name="ProtocolloCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField()),
                (
                    "direzione",
                    models.CharField(
                        choices=[("IN", "Entrata"), ("OUT", "Uscita")], max_length=3
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_counters",
                        to="anagrafiche.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contatore protocollo",
                "verbose_name_plural": "Contatori protocollo",
                "indexes": [
                    models.Index(
                        fields=["cliente", "anno", "direzione"],
                        name="documenti_p_cliente_ff5c1e_idx",
                    )
                ],
                "unique_together": {("cliente", "anno", "direzione")},
            },
        ),
        migrations.CreateModel(
            name="MovimentoProtocollo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direzione",
                    models.CharField(
                        choices=[("IN", "Entrata"), ("OUT", "Uscita")], max_length=3
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("anno", models.PositiveIntegerField(db_index=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "destinatario",
                    models.CharField(
                        blank=True,
                        help_text="A chi consegni in uscita / da chi ricevi in entrata",
                        max_length=255,
                    ),
                ),
                (
                    "chiuso",
                    models.BooleanField(
                        default=False, help_text="Per OUT: flaggato True quando rientra"
                    ),
                ),
                ("data_rientro_prevista", models.DateField(blank=True, null=True)),
                ("causale", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimenti",
                        to="anagrafiche.anagrafica",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimenti",
                        to="documenti.documento",
                    ),
                ),
                (
                    "operatore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rientro_di",
                    models.OneToOneField(
                        blank=True,
                        help_text="Se questo è un IN di rientro, indica l'OUT chiuso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rientrato_con",
                        to="documenti.movimentoprotocollo",
                    ),
                ),
                (
                    "ubicazione",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collocazione fisica in entrata",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documenti.ubicazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento di protocollo",
                "verbose_name_plural": "Movimenti di protocollo",
                "ordering": ["cliente", "anno", "direzione", "numero"],
                "indexes": [
                    models.Index(
                        fields=["documento", "direzione", "chiuso"],
                        name="documenti_m_documen_e02e94_idx",
                    ),
                    models.Index(
                        fields=["cliente", "anno", "direzione", "numero"],
                        name="documenti_m_cliente_88c641_idx",
                    ),
                    models.Index(
                        condition=models.Q(("chiuso", False), ("direzione", "OUT")),
                        fields=["documento"],
                        name="mov_out_aperti_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.UniqueConstraint(
                fields=("cliente", "anno", "direzione", "numero"),
                name="uniq_protocollo_per_cliente_anno_dir_num",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("direzione", "IN"), ("rientro_di__isnull", True), _connector="OR"
                ),
                name="rientro_di_solo_per_IN",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("anno", django.db.models.functions.datetime.ExtractYear("data"))
                ),
                name="anno_coerente_con_data",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimentoprotocollo",
            constraint=models.CheckConstraint(
                check=models.Q(("numero__gt", 0)), name="numero_maggiore_zero"
            ),
        ),
        migrations.AddIndex(
            model_name="documentocounter",
            index=models.Index(
                fields=["cliente", "anno"], name="documenti_d_cliente_404aef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentocounter",
            unique_together={("cliente", "anno")},
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["cliente", "tipo", "data_documento"],
                name="documenti_d_cliente_aac72d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["stato"], name="documenti_d_stato_77a0ea_idx"),
        ),
        migrations.AddIndex(
            model_name="attributovalore",
            index=models.Index(
                fields=["documento", "definizione"],
                name="documenti_a_documen_a26df3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attributovalore",
            unique_together={("documento", "definizione")},
        ),
        migrations.AlterUniqueTogether(
            name="attributodefinizione",
            unique_together={("tipo_documento", "codice")},
        ),
    ]
