# Generated by Django 4.2.16 on 2025-10-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="protocollocounter",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="protocollocounter",
            name="cliente",
        ),
        migrations.DeleteModel(
            name="MovimentoProtocollo",
        ),
        migrations.DeleteModel(
            name="ProtocolloCounter",
        ),
    ]
