# Generated by Django 4.2.16 on 2025-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0002_alter_protocollocounter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='digitale',
            field=models.BooleanField(default=True, help_text='Se disattivo il documento è cartaceo e richiede una gestione fisica.'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='stato',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('definitivo', 'Definitivo'), ('archiviato', 'Archiviato'), ('uscito', 'Uscito'), ('consegnato', 'Consegnato'), ('scaricato', 'Scaricato')], db_index=True, default='bozza', max_length=20),
        ),
    ]
