# Generated by Django 4.2.16 on 2025-11-08 10:10

from django.db import migrations, models
import django.db.models.deletion


def _migrate_documento_clienti(apps, schema_editor):
    Documento = apps.get_model("documenti", "Documento")
    DocumentoCounter = apps.get_model("documenti", "DocumentoCounter")
    Cliente = apps.get_model("anagrafiche", "Cliente")
    Anagrafica = apps.get_model("anagrafiche", "Anagrafica")

    db_alias = schema_editor.connection.alias
    vendor = schema_editor.connection.vendor

    def drop_fk_constraints(model):
        if vendor == "sqlite":
            # SQLite ricrea la tabella durante AlterField, non supporta DROP CONSTRAINT.
            return
        field = model._meta.get_field("cliente")
        column = field.column
        table = model._meta.db_table
        constraint_names = schema_editor._constraint_names(model, [column], foreign_key=True)
        for constraint in constraint_names:
            schema_editor.execute(
                schema_editor.sql_delete_fk
                % {
                    "table": schema_editor.quote_name(table),
                    "name": schema_editor.quote_name(constraint),
                }
            )

    # Rimuove i vincoli attuali verso Anagrafica per poter convertire gli ID
    for model in (Documento, DocumentoCounter):
        drop_fk_constraints(model)

    documento_anag_ids = (
        Documento.objects.using(db_alias)
        .exclude(cliente_id__isnull=True)
        .values_list("cliente_id", flat=True)
    )
    counter_anag_ids = (
        DocumentoCounter.objects.using(db_alias)
        .exclude(cliente_id__isnull=True)
        .values_list("cliente_id", flat=True)
    )

    needed_anag_ids = set(documento_anag_ids) | set(counter_anag_ids)
    if not needed_anag_ids:
        return

    existing_map = dict(
        Cliente.objects.using(db_alias)
        .filter(anagrafica_id__in=needed_anag_ids)
        .values_list("anagrafica_id", "id")
    )

    missing_ids = [anag_id for anag_id in needed_anag_ids if anag_id not in existing_map]
    if missing_ids:
        valid_anagrafiche = set(
            Anagrafica.objects.using(db_alias)
            .filter(id__in=missing_ids)
            .values_list("id", flat=True)
        )
        missing_to_create = [anag_id for anag_id in missing_ids if anag_id in valid_anagrafiche]
        if missing_to_create:
            for anag_id in missing_to_create:
                cliente = Cliente.objects.using(db_alias).create(anagrafica_id=anag_id)
                existing_map[anag_id] = cliente.id

    for anag_id, cliente_id in existing_map.items():
        Documento.objects.using(db_alias).filter(cliente_id=anag_id).update(cliente_id=cliente_id)
        DocumentoCounter.objects.using(db_alias).filter(cliente_id=anag_id).update(cliente_id=cliente_id)


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0004_anagrafica_codice"),
        ("documenti", "0003_documento_digitale_alter_documento_stato"),
    ]

    operations = [
        migrations.RunPython(_migrate_documento_clienti, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documenti",
                to="anagrafiche.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="documentocounter",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documento_counters",
                to="anagrafiche.cliente",
            ),
        ),
    ]
