# Generated by Django 5.2.8 on 2025-11-20 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0004_alter_documento_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(help_text='Percorso completo del file sul filesystem locale', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('completed', 'Completato'), ('failed', 'Fallito'), ('cancelled', 'Annullato')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Dimensione del file in bytes', null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='documenti.documento')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta eliminazione file',
                'verbose_name_plural': 'Richieste eliminazione file',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='documenti_f_status_1501fe_idx'), models.Index(fields=['documento', 'status'], name='documenti_f_documen_372664_idx')],
            },
        ),
    ]
