# Generated by Django 5.2.8 on 2025-12-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0007_documento_popola_ubicazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitipo',
            name='nome_file_pattern',
            field=models.CharField(blank=True, help_text='Pattern nome file: token {id}, {tipo.codice}, {data_documento:%Y%m%d}, {attr:<codice>}, {cliente.<campo>}, {slug:descrizione}, {upper:...}/{lower:...}, {if:attr:<codice>:TESTO}/{ifnot:field:<campo>:TESTO}.', max_length=255),
        ),
    ]
