# Generated by Django 5.2.8 on 2026-01-29 12:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0008_alter_documentitipo_nome_file_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentitipo",
            name="help_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Struttura JSON contenente tutta la documentazione per questo tipo di documento. Include: descrizione_breve, quando_usare, campi_obbligatori, attributi_dinamici, guida_compilazione, pattern_codice, archiviazione, workflow, note_speciali, faq, risorse_correlate",
                verbose_name="Dati Help",
            ),
        ),
        migrations.AddField(
            model_name="documentitipo",
            name="help_ordine",
            field=models.IntegerField(
                default=0,
                help_text="Ordine di visualizzazione nella sezione help (0 = primo)",
                verbose_name="Ordine visualizzazione help",
            ),
        ),
        migrations.AlterField(
            model_name="documentitipo",
            name="nome_file_pattern",
            field=models.CharField(
                blank=True,
                help_text="Pattern nome file: token {id}, {tipo.codice}, {data_documento:%Y%m%d}, {attr:<codice>}, {attr:<codice>.<campo_anagrafica>}, {cliente.<campo>}, {slug:descrizione}, {upper:...}/{lower:...}, {if:attr:<codice>:TESTO}/{ifnot:field:<campo>:TESTO}. Es: {attr:dipendente.codice} per accedere al codice dell'anagrafica collegata.",
                max_length=255,
            ),
        ),
    ]
