# Generated by Django 5.2.8 on 2026-02-05 08:00

import django.core.serializers.json
import django.db.models.deletion
import mygest.storages
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0009_add_help_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "tipo_importazione",
                    models.CharField(
                        choices=[
                            ("cedolini", "Cedolini Paga"),
                            ("unilav", "Comunicazioni UNILAV"),
                            ("f24", "Modelli F24"),
                            ("dichiarazioni_fiscali", "Dichiarazioni Fiscali"),
                            ("contratti", "Contratti"),
                            ("fatture", "Fatture"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "file_originale",
                    models.FileField(
                        help_text="File ZIP o singolo documento caricato dall'utente",
                        storage=mygest.storages.NASPathStorage(),
                        upload_to="import_sessions/%Y/%m/",
                    ),
                ),
                ("file_originale_nome", models.CharField(max_length=500)),
                ("num_documenti_totali", models.IntegerField(default=0)),
                ("num_documenti_importati", models.IntegerField(default=0)),
                ("num_documenti_saltati", models.IntegerField(default=0)),
                ("num_documenti_errore", models.IntegerField(default=0)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("active", "Attiva"),
                            ("completed", "Completata"),
                            ("expired", "Scaduta"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Scadenza sessione (default +48h). Dopo questa data la sessione viene eliminata automaticamente."
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "temp_dir",
                    models.CharField(
                        blank=True,
                        help_text="Directory temporanea dove sono estratti i file (viene pulita dopo expire)",
                        max_length=500,
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        help_text="Utente che ha avviato l'importazione",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessione di Importazione",
                "verbose_name_plural": "Sessioni di Importazione",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportSessionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path assoluto o relativo al temp_dir della sessione",
                        max_length=1000,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        default=0, help_text="Dimensione file in bytes"
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Dati estratti dal parser (struttura dipende dal tipo importazione)",
                    ),
                ),
                (
                    "anagrafiche_reperite",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Lista anagrafiche trovate nel DB: [{id, cf, nome, match_type, ruolo}]",
                    ),
                ),
                (
                    "valori_editabili",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Campi che l'utente può modificare prima dell'importazione",
                    ),
                ),
                (
                    "mappatura_db",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Preview dei campi che verranno salvati nel DB (tipo, attributi, note_preview)",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("pending", "Da importare"),
                            ("imported", "Importato"),
                            ("skipped", "Saltato"),
                            ("error", "Errore"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ordine",
                    models.IntegerField(
                        default=0,
                        help_text="Posizione nella lista documenti (per ordinamento UI)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Messaggio errore user-friendly"
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Traceback completo per debugging"
                    ),
                ),
                (
                    "parsed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando è stato parsato il documento",
                        null=True,
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando è stato importato/creato il documento",
                        null=True,
                    ),
                ),
                (
                    "documento_creato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Documento creato dopo l'importazione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_source",
                        to="documenti.documento",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documenti.importsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Sessione Importazione",
                "verbose_name_plural": "Documenti Sessione Importazione",
                "ordering": ["session", "ordine", "filename"],
            },
        ),
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(fields=["uuid"], name="documenti_i_uuid_55532d_idx"),
        ),
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(
                fields=["utente", "-created_at"], name="documenti_i_utente__cafeac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(
                fields=["stato", "expires_at"], name="documenti_i_stato_200990_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(
                fields=["tipo_importazione", "-created_at"],
                name="documenti_i_tipo_im_612e75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importsessiondocument",
            index=models.Index(
                fields=["session", "stato"], name="documenti_i_session_01d45b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importsessiondocument",
            index=models.Index(fields=["uuid"], name="documenti_i_uuid_b284ba_idx"),
        ),
        migrations.AddIndex(
            model_name="importsessiondocument",
            index=models.Index(
                fields=["session", "ordine"], name="documenti_i_session_96b6c1_idx"
            ),
        ),
    ]
