# Generated by Django 5.2.8 on 2026-02-05 11:41

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0010_importsession_importsessiondocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentitipo",
            name="duplicate_detection_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Criteri per identificare documenti duplicati. Struttura JSON: {'enabled': bool, 'strategy': str, 'fields': [...], 'scope': {...}}. Esempio: {'enabled': true, 'strategy': 'exact_match', 'fields': [{'type': 'attribute', 'code': 'numero_cedolino'}]}",
                verbose_name="Configurazione rilevamento duplicati",
            ),
        ),
    ]
