# Generated by Django 5.2.8 on 2026-02-05 11:41

from django.db import migrations


def configure_bpag_duplicates(apps, schema_editor):
    """
    Configura rilevamento duplicati per tipo documento BPAG (Cedolini).
    
    Criteri:
    - Scope: stesso cliente
    - Campi: numero_cedolino E data_ora_cedolino (se entrambi presenti)
    - Strategy: exact_match
    """
    DocumentiTipo = apps.get_model('documenti', 'DocumentiTipo')
    
    config = {
        "enabled": True,
        "strategy": "exact_match",
        "scope": {
            "cliente": True,
            "anno": False,
            "fascicolo": False
        },
        "fields": [
            {
                "type": "attribute",
                "code": "numero_cedolino",
                "required": False,
                "weight": 1.0,
                "normalize": True,
                "case_sensitive": False
            },
            {
                "type": "attribute",
                "code": "data_ora_cedolino",
                "required": False,
                "weight": 1.0,
                "normalize": True
            }
        ],
        "match_mode": "all_required_or_any_weighted"
    }
    
    try:
        bpag = DocumentiTipo.objects.get(codice='BPAG')
        bpag.duplicate_detection_config = config
        bpag.save(update_fields=['duplicate_detection_config'])
        print(f"✅ Configurato rilevamento duplicati per BPAG")
    except DocumentiTipo.DoesNotExist:
        print("⚠️  Tipo BPAG non trovato, verrà configurato alla creazione")


def reverse_configuration(apps, schema_editor):
    """Rimuovi configurazione duplicati per BPAG"""
    DocumentiTipo = apps.get_model('documenti', 'DocumentiTipo')
    
    try:
        bpag = DocumentiTipo.objects.get(codice='BPAG')
        bpag.duplicate_detection_config = {}
        bpag.save(update_fields=['duplicate_detection_config'])
    except DocumentiTipo.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0011_add_duplicate_detection_config"),
    ]

    operations = [
        migrations.RunPython(
            configure_bpag_duplicates,
            reverse_code=reverse_configuration
        ),
    ]
