# Generated by Django 4.2.16 on 2026-05-11 10:30

from django.db import migrations, models
import documenti.models
import documenti.validators
import mygest.storages


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0012_configure_bpag_duplicate_detection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=mygest.storages.NASPathStorage(),
                upload_to=documenti.models.documento_upload_to,
                validators=[documenti.validators.validate_file_content],
            ),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="tipo_importazione",
            field=models.CharField(
                choices=[
                    ("cedolini", "Cedolini Paga"),
                    ("certificazioni_uniche", "Certificazioni Uniche"),
                    ("unilav", "Comunicazioni UNILAV"),
                    ("f24", "Modelli F24"),
                    ("dichiarazioni_fiscali", "Dichiarazioni Fiscali"),
                    ("contratti", "Contratti"),
                    ("fatture", "Fatture"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
