"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ARCHIVIO_BASE_PATH = "/mnt/archivio"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3#@bl+qgh$rvlp1y(cp4)@#*0)^%-giw17ruqpl9ulw^sf+rnp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*","localhost","127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anagrafiche',
    'pratiche',
    'fascicoli',
    'documenti',
    # "classificazione",  # rimosso
    'stampe',
    "archivio_fisico",
    "titolario",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static & Media
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Template base del progetto
TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]

# NAS
ARCHIVIO_BASE_PATH = "/mnt/archivio"  # condivisa SMB già montata

# (opzionale) FileSystemStorage per NAS
from django.core.files.storage import FileSystemStorage
NAS_STORAGE = FileSystemStorage(location=ARCHIVIO_BASE_PATH)

# Directory da scandire per l’import (puoi elencarne più d’una)
IMPORTAZIONI_SOURCE_DIRS = [
    "/home/sandro/documenti", "/mnt/archivio/importazioni"
]
# Directory di destinazione (default: MEDIA_ROOT/importazioni/raccolta)
# IMPORTAZIONI_DEST_DIR = "/home/sandro/manager_pratiche_media/importazioni/raccolta"

# OCR per PDF scansionati
CLASSIFICAZIONE_OCR_ENABLED = True
CLASSIFICAZIONE_OCR_LANG = "ita+eng"    # lingue Tesseract installate
CLASSIFICAZIONE_OCR_DPI = 200           # 150–300 bilancia qualità/velocità
CLASSIFICAZIONE_OCR_MAX_PAGES = 10      # limita pagine per performance (0 = nessun limite)
# POPPLER_PATH = "/usr/bin"             # opzionale, se pdf2image non trova poppler

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/classificazione/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
# Assicurati che TEMPLATES['DIRS'] includa la cartella templates del progetto

DYMO_PRINTER_NAME = "DYMO_LabelWriter_450"  # sostituisci con la queue CUPS
ETICHETTE_SERVER_PRINT = False  # disabilita stampa diretta (lp)
# Margine di default per le etichette (in millimetri)
ETICHETTE_MARGIN_MM = 10.0

DOCUMENTI_FILE_PATTERN_DEFAULT = "{tipo.codice}_{id}_{attr:repertorio_atto|REPNA}_{data_documento:%Y%m%d}_{slug:descrizione}.pdf"
DOCUMENTI_RENAME_ONLY_NEW = True         # Rinominare solo al primo salvataggio
DOCUMENTI_FILENAME_MAX_LEN = 140         # Lunghezza massima basename (senza path)
DOCUMENTI_PATTERN_ENABLE_UNIQUE = True   # Se True forza suffisso incrementale se conflitto