# Generated by Django 4.2.16 on 2025-10-19 11:37

import anagrafiche.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anagrafica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PF", "Persona fisica"), ("PG", "Persona giuridica")],
                        db_index=True,
                        default="PF",
                        max_length=2,
                    ),
                ),
                ("ragione_sociale", models.CharField(blank=True, max_length=200)),
                ("nome", models.CharField(blank=True, max_length=120)),
                ("cognome", models.CharField(blank=True, max_length=120)),
                (
                    "codice_fiscale",
                    models.CharField(
                        help_text="PF: 16 caratteri; PG: 11 cifre (validato come P.IVA).",
                        max_length=16,
                        unique=True,
                        validators=[anagrafiche.models.validate_codice_fiscale],
                        verbose_name="Codice fiscale",
                    ),
                ),
                (
                    "partita_iva",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[anagrafiche.models.validate_piva],
                        verbose_name="Partita IVA",
                    ),
                ),
                ("pec", models.EmailField(blank=True, max_length=254)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("indirizzo", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "verbose_name": "Anagrafica",
                "verbose_name_plural": "Anagrafiche",
                "ordering": ["tipo", "ragione_sociale", "cognome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="AnagraficaDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(db_index=True)),
                ("codice_fiscale", models.CharField(max_length=16)),
                ("display_name", models.CharField(max_length=255)),
                ("deleted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Anagrafica cancellata",
                "verbose_name_plural": "Anagrafiche cancellate",
                "ordering": ["-deleted_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientiTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        help_text="Identificativo breve e univoco (es. PRIV, AZI, ENTE).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        db_index=True,
                        help_text="Descrizione leggibile del tipo cliente (es. Privato, Azienda).",
                        max_length=120,
                    ),
                ),
                ("slug", models.SlugField(blank=True, editable=False)),
            ],
            options={
                "verbose_name": "Tipo cliente",
                "verbose_name_plural": "Tipi cliente",
                "ordering": ["descrizione"],
            },
        ),
        migrations.CreateModel(
            name="Indirizzo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_indirizzo",
                    models.CharField(
                        choices=[
                            ("RES", "Residenza"),
                            ("DOM", "Domicilio"),
                            ("SLE", "Sede legale"),
                            ("SAM", "Sede amministrativa"),
                        ],
                        max_length=3,
                        verbose_name="Tipo indirizzo",
                    ),
                ),
                (
                    "toponimo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Toponimo (via, viale, piazza…)",
                    ),
                ),
                (
                    "indirizzo",
                    models.CharField(max_length=255, verbose_name="Indirizzo"),
                ),
                (
                    "numero_civico",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numero civico"
                    ),
                ),
                (
                    "frazione",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Frazione"
                    ),
                ),
                ("cap", models.CharField(blank=True, max_length=5, verbose_name="CAP")),
                ("comune", models.CharField(max_length=120, verbose_name="Comune")),
                (
                    "provincia",
                    models.CharField(
                        blank=True,
                        help_text="Sigla (es. MI)",
                        max_length=2,
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "nazione",
                    models.CharField(
                        default="IT",
                        help_text="ISO 3166-1 alpha-2 (es. IT)",
                        max_length=2,
                        verbose_name="Nazione",
                    ),
                ),
                (
                    "principale",
                    models.BooleanField(default=False, verbose_name="Principale"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Note"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indirizzi",
                        to="anagrafiche.anagrafica",
                        verbose_name="Anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indirizzo",
                "verbose_name_plural": "Indirizzi",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente_dal",
                    models.DateField(
                        blank=True,
                        help_text="Data inizio validità come cliente.",
                        null=True,
                        verbose_name="Cliente dal",
                    ),
                ),
                (
                    "cliente_al",
                    models.DateField(
                        blank=True,
                        help_text="Data fine validità (opzionale).",
                        null=True,
                        verbose_name="Cliente al",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Note"),
                ),
                (
                    "anagrafica",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente",
                        to="anagrafiche.anagrafica",
                        verbose_name="Anagrafica",
                    ),
                ),
                (
                    "tipo_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="tipoCliente",
                        help_text="Classificazione del cliente.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clienti",
                        to="anagrafiche.clientitipo",
                        verbose_name="Tipo cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clienti",
            },
        ),
        migrations.AddIndex(
            model_name="anagrafica",
            index=models.Index(fields=["tipo"], name="anagrafiche_tipo_78bd62_idx"),
        ),
        migrations.AddIndex(
            model_name="anagrafica",
            index=models.Index(
                fields=["codice_fiscale"], name="anagrafiche_codice__ec6412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anagrafica",
            index=models.Index(fields=["pec"], name="anagrafiche_pec_fd0acd_idx"),
        ),
        migrations.AddIndex(
            model_name="anagrafica",
            index=models.Index(fields=["email"], name="anagrafiche_email_567e88_idx"),
        ),
        migrations.AddIndex(
            model_name="anagrafica",
            index=models.Index(
                fields=["telefono"], name="anagrafiche_telefon_58ed4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anagrafica",
            index=models.Index(
                fields=["updated_at"], name="anagrafiche_updated_173e7a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anagrafica",
            constraint=models.UniqueConstraint(
                condition=models.Q(("partita_iva", ""), _negated=True),
                fields=("partita_iva",),
                name="uniq_partita_iva_non_vuota",
            ),
        ),
        migrations.AddConstraint(
            model_name="anagrafica",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pec", ""), _negated=True),
                fields=("pec",),
                name="uniq_pec_non_vuota",
            ),
        ),
        migrations.AddIndex(
            model_name="indirizzo",
            index=models.Index(
                fields=["anagrafica", "tipo_indirizzo"],
                name="anagrafiche_anagraf_a122ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indirizzo",
            index=models.Index(
                fields=["comune", "provincia"], name="anagrafiche_comune_7d4f38_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="indirizzo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principale", True)),
                fields=("anagrafica", "tipo_indirizzo"),
                name="uniq_indirizzo_principale_per_tipo",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["anagrafica"], name="anagrafiche_anagraf_ba4b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["tipo_cliente"], name="anagrafiche_tipoCli_880fa2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("cliente_al__isnull", True), ("cliente_dal__isnull", True)
                    ),
                    models.Q(
                        ("cliente_al__isnull", True), ("cliente_dal__isnull", False)
                    ),
                    models.Q(
                        ("cliente_al__gte", models.F("cliente_dal")),
                        ("cliente_al__isnull", False),
                        ("cliente_dal__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="cliente_intervallo_date_valido",
            ),
        ),
    ]
