# Generated by Django 4.2.16 on 2025-10-19 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="codice_destinatario",
            field=models.CharField(
                blank=True,
                help_text="7 caratteri alfanumerici. Per PRIVATO deve essere '0000000'.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]{7}$", "Deve contenere 7 caratteri A-Z o 0-9."
                    )
                ],
                verbose_name="Codice destinatario SDI",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="indirizzo_consegna",
            field=models.ForeignKey(
                blank=True,
                help_text="Se non impostato, verrà usato l'indirizzo principale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clienti_consegna",
                to="anagrafiche.indirizzo",
                verbose_name="Indirizzo di consegna",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="indirizzo_fatturazione",
            field=models.ForeignKey(
                blank=True,
                help_text="Se non impostato, verrà usato l'indirizzo principale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clienti_fatturazione",
                to="anagrafiche.indirizzo",
                verbose_name="Indirizzo di fatturazione",
            ),
        ),
    ]
