# Generated by Django 4.2.16 on 2025-10-19 16:57

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0002_cliente_codice_destinatario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="codice_destinatario",
            field=models.CharField(
                blank=True,
                help_text="7 caratteri alfanumerici. Per PRIVATO deve essere '0000000'.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Deve contenere 7 caratteri A-Z o 0-9.",
                        regex="^[A-Z0-9]{7}$",
                    )
                ],
                verbose_name="Codice destinatario SDI",
            ),
        ),
        migrations.AlterField(
            model_name="indirizzo",
            name="tipo_indirizzo",
            field=models.CharField(
                choices=[
                    ("RES", "Residenza"),
                    ("DOM", "Domicilio"),
                    ("SLE", "Sede legale"),
                    ("SAM", "Sede amministrativa"),
                    ("UFI", "Ufficio"),
                    ("ALT", "Altro"),
                ],
                max_length=3,
                verbose_name="Tipo indirizzo",
            ),
        ),
    ]
