# Generated by Django 4.2.16 on 2025-10-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0003_alter_cliente_codice_destinatario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anagrafica",
            name="codice",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Codice cliente CLI (6+2), maiuscolo alfanumerico",
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
    ]
