# Generated by Django 4.2.16 on 2025-11-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_anagrafica_codice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('GEN', 'Generico'), ('PEC', 'PEC'), ('AMM', 'Amministrativo'), ('COM', 'Commerciale'), ('TEC', 'Tecnico'), ('ALT', 'Altro')], default='GEN', max_length=3)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_preferito', models.BooleanField(default=False, help_text='Segna il contatto come prioritario.')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anagrafica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatti_email', to='anagrafiche.anagrafica')),
            ],
            options={
                'verbose_name': 'Contatto email',
                'verbose_name_plural': 'Contatti email',
                'ordering': ['anagrafica', '-is_preferito', 'nominativo', 'email'],
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('attiva', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mailing list',
                'verbose_name_plural': 'Mailing list',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MailingListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(blank=True, help_text='Ruolo del contatto nella lista (es. CC, referente).', max_length=40)),
                ('contatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='anagrafiche.emailcontatto')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='anagrafiche.mailinglist')),
            ],
            options={
                'verbose_name': 'Iscrizione mailing list',
                'verbose_name_plural': 'Iscrizioni mailing list',
                'unique_together': {('mailing_list', 'contatto')},
            },
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='contatti',
            field=models.ManyToManyField(blank=True, related_name='liste', through='anagrafiche.MailingListMembership', to='anagrafiche.emailcontatto'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_lists', to='anagrafiche.anagrafica'),
        ),
        migrations.CreateModel(
            name='MailingListIndirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nominativo', models.CharField(blank=True, max_length=120)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi_extra', to='anagrafiche.mailinglist')),
            ],
            options={
                'verbose_name': 'Indirizzo mailing list',
                'verbose_name_plural': 'Indirizzi mailing list',
                'unique_together': {('mailing_list', 'email')},
            },
        ),
        migrations.AddConstraint(
            model_name='emailcontatto',
            constraint=models.UniqueConstraint(fields=('anagrafica', 'email', 'tipo'), name='uniq_contatto_email_per_tipo'),
        ),
    ]
