# Generated by Django 5.2.8 on 2025-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "anagrafiche",
            "0005_emailcontatto_mailinglist_mailinglistmembership_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="indirizzo",
            name="uniq_indirizzo_principale_per_tipo",
        ),
        migrations.AddConstraint(
            model_name="indirizzo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principale", True)),
                fields=("anagrafica",),
                name="uniq_indirizzo_principale_per_anagrafica",
            ),
        ),
    ]
