# Generated by Django 5.2.8 on 2025-11-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0006_sync_indirizzo_email_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indirizzo",
            name="provincia",
            field=models.CharField(
                blank=True,
                help_text="Sigla (es. MI)",
                max_length=3,
                verbose_name="Provincia",
            ),
        ),
        migrations.CreateModel(
            name="ComuneItaliano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice_istat",
                    models.CharField(
                        db_index=True,
                        help_text="Codice ISTAT a 6 cifre del comune",
                        max_length=6,
                        unique=True,
                        verbose_name="Codice ISTAT",
                    ),
                ),
                (
                    "codice_belfiore",
                    models.CharField(
                        db_index=True,
                        help_text="Codice catastale del comune",
                        max_length=4,
                        verbose_name="Codice catastale (Belfiore)",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True,
                        help_text="Denominazione ufficiale italiana",
                        max_length=120,
                        verbose_name="Nome comune",
                    ),
                ),
                (
                    "nome_alternativo",
                    models.CharField(
                        blank=True,
                        help_text="Denominazione italiana alternativa",
                        max_length=120,
                        verbose_name="Nome alternativo",
                    ),
                ),
                (
                    "provincia",
                    models.CharField(
                        db_index=True,
                        help_text="Sigla provincia (es. MI, RM)",
                        max_length=2,
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "nome_provincia",
                    models.CharField(
                        help_text="Denominazione completa provincia",
                        max_length=120,
                        verbose_name="Nome provincia",
                    ),
                ),
                (
                    "regione",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="Regione"
                    ),
                ),
                (
                    "codice_regione",
                    models.CharField(
                        help_text="Codice ISTAT regione",
                        max_length=2,
                        verbose_name="Codice regione",
                    ),
                ),
                (
                    "cap",
                    models.CharField(
                        db_index=True,
                        help_text="Codice Avviamento Postale",
                        max_length=5,
                        verbose_name="CAP",
                    ),
                ),
                (
                    "flag_capoluogo",
                    models.CharField(
                        choices=[("SI", "Sì"), ("NO", "No")],
                        default="NO",
                        help_text="Indica se è capoluogo di provincia/città metropolitana",
                        max_length=2,
                        verbose_name="Capoluogo",
                    ),
                ),
                (
                    "latitudine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitudine",
                    ),
                ),
                (
                    "longitudine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitudine",
                    ),
                ),
                (
                    "attivo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False per comuni soppressi o fusi",
                        verbose_name="Attivo",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Note su soppressioni, fusioni, variazioni",
                        verbose_name="Note",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comune italiano",
                "verbose_name_plural": "Comuni italiani",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        fields=["nome", "provincia"], name="anagrafiche_nome_fc2151_idx"
                    ),
                    models.Index(
                        fields=["provincia", "nome"],
                        name="anagrafiche_provinc_25c31c_idx",
                    ),
                    models.Index(fields=["cap"], name="anagrafiche_cap_60a74d_idx"),
                    models.Index(
                        fields=["codice_belfiore"],
                        name="anagrafiche_codice__454e6b_idx",
                    ),
                    models.Index(
                        fields=["attivo", "provincia"],
                        name="anagrafiche_attivo_cfcd2d_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="indirizzo",
            name="comune_italiano",
            field=models.ForeignKey(
                blank=True,
                help_text="Se selezionato, CAP/Comune/Provincia vengono compilati automaticamente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="indirizzi",
                to="anagrafiche.comuneitaliano",
                verbose_name="Comune italiano",
            ),
        ),
    ]
