# Generated by Django 4.2.16 on 2025-12-02 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0007_alter_indirizzo_provincia_comuneitaliano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcontatto",
            name="marketing_consent",
            field=models.BooleanField(
                default=False, help_text="Il contatto ha autorizzato invii marketing."
            ),
        ),
        migrations.AddField(
            model_name="emailcontatto",
            name="marketing_consent_acquired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailcontatto",
            name="marketing_consent_source",
            field=models.CharField(
                blank=True,
                help_text="Es. modulo web, contratto, operatore.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="finalita",
            field=models.CharField(
                choices=[
                    ("SERVIZIO", "Comunicazioni di servizio / obbligatorie"),
                    ("MARKETING", "Marketing e aggiornamenti volontari"),
                ],
                default="SERVIZIO",
                help_text="Determina se la lista richiede consenso marketing esplicito.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="informativa_privacy_url",
            field=models.URLField(
                blank=True,
                help_text="Link all'informativa privacy specifica mostrata in fase di consenso.",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="note_consenso",
            field=models.TextField(
                blank=True,
                help_text="Annotazioni operative sul consenso (es. campagna, clausole).",
            ),
        ),
        migrations.AddField(
            model_name="mailinglistindirizzo",
            name="disiscritto_il",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailinglistindirizzo",
            name="marketing_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mailinglistindirizzo",
            name="marketing_consent_acquired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailinglistindirizzo",
            name="marketing_consent_source",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="mailinglistmembership",
            name="disiscritto_il",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailinglistmembership",
            name="disiscritto_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="MailingListUnsubscribeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "contatto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_tokens",
                        to="anagrafiche.emailcontatto",
                    ),
                ),
                (
                    "indirizzo_extra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_tokens",
                        to="anagrafiche.mailinglistindirizzo",
                    ),
                ),
                (
                    "mailing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_tokens",
                        to="anagrafiche.mailinglist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token disiscrizione mailing list",
                "verbose_name_plural": "Token disiscrizione mailing list",
                "ordering": ["-created_at"],
            },
        ),
    ]
