# Generated by Django 5.2.8 on 2025-12-09 11:34

from django.db import migrations, models


def popola_denominazione_abbreviata(apps, schema_editor):
    """
    Popola il campo denominazione_abbreviata con i primi 15 caratteri 
    (senza spazi) della denominazione_anagrafica
    """
    Anagrafica = apps.get_model("anagrafiche", "Anagrafica")
    
    for anagrafica in Anagrafica.objects.all():
        # Calcola la denominazione in base al tipo
        if anagrafica.tipo == "PF":  # Persona fisica
            denominazione = f"{anagrafica.cognome} {anagrafica.nome}".strip()
        else:  # Persona giuridica
            denominazione = anagrafica.ragione_sociale
        
        # Rimuove gli spazi e prende i primi 15 caratteri
        denominazione_senza_spazi = denominazione.replace(" ", "")
        anagrafica.denominazione_abbreviata = denominazione_senza_spazi[:15]
        anagrafica.save(update_fields=["denominazione_abbreviata"])


def reverse_popola_denominazione_abbreviata(apps, schema_editor):
    """
    Reverse: imposta denominazione_abbreviata a None per tutte le anagrafiche
    """
    Anagrafica = apps.get_model("anagrafiche", "Anagrafica")
    Anagrafica.objects.all().update(denominazione_abbreviata=None)


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0008_emailcontatto_marketing_consent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anagrafica",
            name="denominazione_abbreviata",
            field=models.TextField(
                blank=True,
                help_text="Denominazione abbreviata (primi 15 caratteri senza spazi)",
                null=True,
            ),
        ),
        migrations.RunPython(
            popola_denominazione_abbreviata,
            reverse_code=reverse_popola_denominazione_abbreviata,
        ),
    ]
