# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pratiche", "0001_initial"),
        ("anagrafiche", "0001_initial"),
        ("titolario", "0001_initial"),
        ("archivio_fisico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fascicolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField()),
                ("titolo", models.CharField(max_length=200)),
                ("codice", models.CharField(blank=True, max_length=80, unique=True)),
                ("progressivo", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "sub_progressivo",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("corrente", "Archivio corrente"),
                            ("storico", "Archivio storico"),
                            ("chiuso", "Chiuso"),
                            ("deposito", "Deposito"),
                            ("archivio_deposito", "Archivio in deposito"),
                        ],
                        default="corrente",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("retention_anni", models.PositiveIntegerField(default=10)),
                ("protocollo_numero", models.CharField(blank=True, max_length=50)),
                ("protocollo_data", models.DateField(blank=True, null=True)),
                (
                    "path_archivio",
                    models.CharField(blank=True, editable=False, max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fascicoli",
                        to="anagrafiche.anagrafica",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sottofascicoli",
                        to="fascicoli.fascicolo",
                    ),
                ),
                (
                    "pratica",
                    models.OneToOneField(
                        blank=True,
                        help_text="Se indicata, il cliente viene ereditato dalla pratica.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fascicolo",
                        to="pratiche.pratica",
                    ),
                ),
                (
                    "titolario_voce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fascicoli",
                        to="titolario.titolariovoce",
                    ),
                ),
                (
                    "ubicazione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fascicoli",
                        to="archivio_fisico.collocazionefisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fascicolo",
                "verbose_name_plural": "Fascicoli",
            },
        ),
        migrations.CreateModel(
            name="SottofascicoloCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_counter",
                        to="fascicoli.fascicolo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FascicoloCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fascicolo_counters",
                        to="anagrafiche.anagrafica",
                    ),
                ),
                (
                    "titolario_voce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fascicolo_counters",
                        to="titolario.titolariovoce",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cliente", "titolario_voce", "anno"],
                        name="fascicoli_f_cliente_683734_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fascicolocounter",
            constraint=models.UniqueConstraint(
                fields=("cliente", "titolario_voce", "anno"),
                name="uniq_fascicolo_counter_key",
            ),
        ),
        migrations.AddIndex(
            model_name="fascicolo",
            index=models.Index(
                fields=["cliente", "titolario_voce", "anno", "progressivo"],
                name="fascicoli_f_cliente_65ecf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fascicolo",
            index=models.Index(
                fields=["parent", "sub_progressivo"],
                name="fascicoli_f_parent__7ca15c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fascicolo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("parent__isnull", True), ("sub_progressivo", 0)),
                    models.Q(("parent__isnull", False), ("progressivo", 0)),
                    _connector="OR",
                ),
                name="chk_progressivi_coerenti",
            ),
        ),
        migrations.AddConstraint(
            model_name="fascicolo",
            constraint=models.CheckConstraint(
                check=models.Q(("progressivo__gte", 0), ("sub_progressivo__gte", 0)),
                name="chk_progressivi_pos",
            ),
        ),
    ]
