# Generated by Django 4.2.16 on 2025-10-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fascicoli", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fascicolo",
            name="protocollo_data",
        ),
        migrations.RemoveField(
            model_name="fascicolo",
            name="protocollo_numero",
        ),
    ]
