# Generated by Django 4.2.16 on 2025-10-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archivio_fisico", "0004_ubicazione"),
        ("fascicoli", "0003_ubicazione_to_unita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fascicolo",
            name="ubicazione",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fascicoli",
                to="archivio_fisico.unitafisica",
            ),
        ),
    ]
