# Generated by Django 4.2.16 on 2025-10-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0004_anagrafica_codice"),
        ("fascicoli", "0005_pratiche_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fascicolo",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anagrafiche.cliente",
            ),
        ),
    ]
