# Generated by Django 4.2.16 on 2025-11-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fascicoli", "0006_alter_fascicolo_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fascicolo",
            name="stato",
            field=models.CharField(
                choices=[
                    ("corrente", "Archivio corrente"),
                    ("storico", "Archivio storico"),
                    ("chiuso", "Chiuso"),
                    ("deposito", "Deposito"),
                    ("archivio_deposito", "Archivio in deposito"),
                    ("scaricato", "Scaricato"),
                ],
                default="corrente",
                max_length=20,
            ),
        ),
    ]
