# Generated by Django 5.2.8 on 2026-01-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fascicoli", "0007_alter_fascicolo_stato"),
    ]

    operations = [
        migrations.AddField(
            model_name="fascicolo",
            name="fascicoli_collegati",
            field=models.ManyToManyField(
                blank=True,
                help_text="Altri fascicoli collegati a questo fascicolo",
                related_name="collegato_da",
                to="fascicoli.fascicolo",
            ),
        ),
    ]
