# Generated by Django 5.2.8 on 2026-02-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0009_anagrafica_denominazione_abbreviata"),
        ("fascicoli", "0008_fascicolo_fascicoli_collegati"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fascicolocounter",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fascicolo_counters",
                to="anagrafiche.anagrafica",
            ),
        ),
    ]
