# Generated by Django 5.2.8 on 2025-11-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="whatsappconversation",
            new_name="whatsapp_wh_account_048a64_idx",
            old_name="whatsapp_co_account_31bad8_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappconversation",
            new_name="whatsapp_wh_convers_08e42b_idx",
            old_name="whatsapp_co_convers_1c75fb_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappmessage",
            new_name="whatsapp_wh_account_1af582_idx",
            old_name="whatsapp_me_account_9cfbc7_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappmessage",
            new_name="whatsapp_wh_contact_ddc64c_idx",
            old_name="whatsapp_me_contact_c7622c_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappmessage",
            new_name="whatsapp_wh_created_e0ca2a_idx",
            old_name="whatsapp_me_created_d3385c_idx",
        ),
    ]
