# Generated by Django 4.2.16 on 2025-10-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documenti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StampaFormato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "larghezza_mm",
                    models.FloatField(help_text="Larghezza pagina in millimetri"),
                ),
                (
                    "altezza_mm",
                    models.FloatField(help_text="Altezza pagina in millimetri"),
                ),
                (
                    "orientamento",
                    models.CharField(
                        choices=[
                            ("P", "Verticale (portrait)"),
                            ("L", "Orizzontale (landscape)"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("margine_top_mm", models.FloatField(default=5.0)),
                ("margine_right_mm", models.FloatField(default=5.0)),
                ("margine_bottom_mm", models.FloatField(default=5.0)),
                ("margine_left_mm", models.FloatField(default=5.0)),
                (
                    "font_nome_default",
                    models.CharField(default="Helvetica", max_length=64),
                ),
                ("font_size_default", models.FloatField(default=10.0)),
                ("attivo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Formato di stampa",
                "verbose_name_plural": "Formati di stampa",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="StampaModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        help_text="Esempio: documenti, anagrafiche, pratiche…",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name in minuscolo, es: documento",
                        max_length=50,
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Usa come modulo predefinito per app+model",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "font_nome",
                    models.CharField(
                        blank=True,
                        help_text="Se vuoto usa il font del formato",
                        max_length=64,
                    ),
                ),
                (
                    "font_size",
                    models.FloatField(
                        blank=True,
                        help_text="Se vuoto usa la dimensione del formato",
                        null=True,
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                (
                    "documento_tipo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se valorizzato, il modulo è valido solo per questo tipo documento",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moduli_stampa",
                        to="documenti.documentitipo",
                    ),
                ),
                (
                    "formato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moduli",
                        to="stampe.stampaformato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modulo di stampa",
                "verbose_name_plural": "Moduli di stampa",
                "ordering": ["app_label", "model_name", "nome"],
                "unique_together": {("app_label", "model_name", "slug")},
            },
        ),
        migrations.CreateModel(
            name="StampaLista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        help_text="Esempio: documenti, anagrafiche, pratiche…",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name in minuscolo, es: documento",
                        max_length=50,
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Usa come lista predefinita per app+model",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "filter_def",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Esempio: {"cliente_id": ":cliente", "stato__in": ["APERTO","CHIUSO"]}',
                    ),
                ),
                (
                    "order_by",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista di field per ordering, es. ["-data", "codice"]',
                    ),
                ),
                (
                    "header_font_name",
                    models.CharField(
                        blank=True, default="Helvetica-Bold", max_length=64
                    ),
                ),
                ("header_font_size", models.FloatField(default=9.0)),
                (
                    "row_font_name",
                    models.CharField(blank=True, default="Helvetica", max_length=64),
                ),
                ("row_font_size", models.FloatField(default=9.0)),
                (
                    "row_max_lines",
                    models.PositiveIntegerField(
                        default=2, help_text="Max righe per cella"
                    ),
                ),
                (
                    "row_spacing",
                    models.FloatField(
                        default=1.2, help_text="Moltiplicatore interlinea (es. 1.2)"
                    ),
                ),
                (
                    "row_height_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Altezza riga forzata (mm). Vuoto = calcolo automatico approssimato",
                        null=True,
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                (
                    "formato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liste",
                        to="stampe.stampaformato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista di stampa",
                "verbose_name_plural": "Liste di stampa",
                "ordering": ["app_label", "model_name", "nome"],
                "unique_together": {("app_label", "model_name", "slug")},
            },
        ),
        migrations.CreateModel(
            name="StampaColonna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("text", "Testo (ATTR)"),
                            ("template", "Template Python format"),
                            ("barcode", "Barcode"),
                            ("qrcode", "QR Code"),
                        ],
                        default="text",
                        max_length=12,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Intestazione colonna", max_length=120),
                ),
                (
                    "attr_path",
                    models.CharField(
                        blank=True,
                        help_text="Percorso attributo (es. cliente.ragione_sociale)",
                        max_length=200,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        help_text="Python format, es: 'CF: {obj.cliente.codice_fiscale}'",
                        max_length=400,
                    ),
                ),
                ("larghezza_mm", models.FloatField(help_text="Larghezza colonna (mm)")),
                (
                    "align",
                    models.CharField(
                        choices=[
                            ("left", "Sinistra"),
                            ("center", "Centro"),
                            ("right", "Destra"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("font_nome", models.CharField(blank=True, max_length=64)),
                ("font_size", models.FloatField(blank=True, null=True)),
                ("max_lines", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "barcode_standard",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("code128", "Code128"),
                            ("code39", "Code39"),
                            ("ean13", "EAN-13"),
                        ],
                        default="code128",
                        max_length=16,
                    ),
                ),
                ("barcode_bar_width_mm", models.FloatField(default=0.3)),
                ("barcode_height_mm", models.FloatField(default=10.0)),
                ("qr_size_mm", models.FloatField(default=12.0)),
                (
                    "qr_error",
                    models.CharField(
                        blank=True,
                        choices=[("L", "L"), ("M", "M"), ("Q", "Q"), ("H", "H")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("visibile", models.BooleanField(default=True)),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colonne",
                        to="stampe.stampalista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colonna lista",
                "verbose_name_plural": "Colonne lista",
                "ordering": ["lista", "ordine", "id"],
            },
        ),
        migrations.CreateModel(
            name="StampaCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("static", "Testo statico"),
                            ("attr", "Campo da oggetto (path)"),
                            ("template", "Template Python format"),
                            ("barcode", "Barcode"),
                            ("qrcode", "QR Code"),
                        ],
                        default="attr",
                        max_length=12,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Etichetta (opzionale)", max_length=120
                    ),
                ),
                (
                    "attr_path",
                    models.CharField(
                        blank=True,
                        help_text="Percorso attributo (es. cliente.ragione_sociale)",
                        max_length=200,
                    ),
                ),
                (
                    "static_value",
                    models.TextField(blank=True, help_text="Valore per testo statico"),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        help_text="Python format, es: 'CF: {cliente.codice_fiscale}'",
                        max_length=400,
                    ),
                ),
                ("x_mm", models.FloatField(help_text="Ascissa da sinistra (mm)")),
                ("y_mm", models.FloatField(help_text="Ordinata dall'alto (mm)")),
                (
                    "larghezza_mm",
                    models.FloatField(
                        blank=True,
                        help_text="Larghezza area testo (wrapping). Vuoto = riga singola senza wrapping",
                        null=True,
                    ),
                ),
                ("font_nome", models.CharField(blank=True, max_length=64)),
                ("font_size", models.FloatField(blank=True, null=True)),
                ("bold", models.BooleanField(default=False)),
                ("italic", models.BooleanField(default=False)),
                (
                    "align",
                    models.CharField(
                        choices=[
                            ("left", "Sinistra"),
                            ("center", "Centro"),
                            ("right", "Destra"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("max_lines", models.PositiveIntegerField(default=1)),
                (
                    "barcode_standard",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("code128", "Code128"),
                            ("code39", "Code39"),
                            ("ean13", "EAN-13"),
                        ],
                        default="code128",
                        max_length=16,
                    ),
                ),
                (
                    "barcode_bar_width_mm",
                    models.FloatField(default=0.3, help_text="Spessore barre (mm)"),
                ),
                (
                    "barcode_height_mm",
                    models.FloatField(default=12.0, help_text="Altezza barre (mm)"),
                ),
                (
                    "qr_size_mm",
                    models.FloatField(default=24.0, help_text="Lato del QR (mm)"),
                ),
                (
                    "qr_error",
                    models.CharField(
                        blank=True,
                        choices=[("L", "L"), ("M", "M"), ("Q", "Q"), ("H", "H")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("visibile", models.BooleanField(default=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campi",
                        to="stampe.stampamodulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo modulo",
                "verbose_name_plural": "Campi modulo",
                "ordering": ["modulo", "ordine", "id"],
            },
        ),
    ]
