# Generated by Django 4.2.16 on 2025-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stampe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stampacampo",
            name="border_color",
            field=models.CharField(
                blank=True,
                help_text="Colore bordo (nome ReportLab o #RRGGBB)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="stampacampo",
            name="border_width_pt",
            field=models.FloatField(default=0.5, help_text="Spessore bordo (pt)"),
        ),
        migrations.AddField(
            model_name="stampacampo",
            name="corner_radius_mm",
            field=models.FloatField(
                default=0.0, help_text="Raggio angoli (mm, solo rettangoli)"
            ),
        ),
        migrations.AddField(
            model_name="stampacampo",
            name="fill_color",
            field=models.CharField(
                blank=True,
                help_text="Colore riempimento (nome ReportLab o #RRGGBB)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="stampacampo",
            name="shape_height_mm",
            field=models.FloatField(default=0.0, help_text="Altezza elemento (mm)"),
        ),
        migrations.AddField(
            model_name="stampacampo",
            name="shape_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rect", "Rettangolo"),
                    ("rounded_rect", "Rettangolo arrotondato"),
                    ("line", "Linea"),
                ],
                default="rect",
                help_text="Tipo elemento grafico",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stampacampo",
            name="shape_width_mm",
            field=models.FloatField(default=0.0, help_text="Larghezza elemento (mm)"),
        ),
        migrations.AlterField(
            model_name="stampacampo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("static", "Testo statico"),
                    ("attr", "Campo da oggetto (path)"),
                    ("template", "Template Python format"),
                    ("barcode", "Barcode"),
                    ("qrcode", "QR Code"),
                    ("shape", "Elemento grafico"),
                ],
                default="attr",
                max_length=12,
            ),
        ),
    ]
