# Generated by Django 4.2.16 on 2025-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stampe",
            "0002_stampacampo_border_color_stampacampo_border_width_pt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stampalista",
            name="intestazione",
            field=models.TextField(
                blank=True,
                help_text="Testo di intestazione (opzionale, anche multilinea)",
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="piedipagina",
            field=models.TextField(
                blank=True,
                help_text="Testo di piè di pagina (opzionale, anche multilinea)",
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo",
            field=models.CharField(
                blank=True,
                help_text="Titolo da mostrare in testa alla stampa",
                max_length=200,
            ),
        ),
    ]
