# Generated by Django 4.2.16 on 2025-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stampe", "0003_stampalista_intestazione_stampalista_piedipagina_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stampalista",
            name="intestazione_font_size",
            field=models.FloatField(
                default=10.0, help_text="Dimensione font intestazione"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="intestazione_x_mm",
            field=models.FloatField(
                default=0.0, help_text="Posizione X intestazione (mm)"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="intestazione_y_mm",
            field=models.FloatField(
                default=0.0, help_text="Posizione Y intestazione (mm, da top)"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="piedipagina_font_size",
            field=models.FloatField(
                default=9.0, help_text="Dimensione font piè di pagina"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="piedipagina_x_mm",
            field=models.FloatField(
                default=0.0, help_text="Posizione X piè di pagina (mm)"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="piedipagina_y_mm",
            field=models.FloatField(
                default=0.0, help_text="Posizione Y piè di pagina (mm, da bottom)"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_bold",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_font_size",
            field=models.FloatField(default=14.0),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_italic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_larghezza_mm",
            field=models.FloatField(
                default=0.0, help_text="Larghezza max titolo (mm, 0=illimitata)"
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_template",
            field=models.CharField(
                blank=True,
                help_text="Template Python format, es: 'Documenti di {obj.cliente} - {attr.codice_fiscale}'",
                max_length=400,
            ),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_x_mm",
            field=models.FloatField(default=0.0, help_text="Posizione X titolo (mm)"),
        ),
        migrations.AddField(
            model_name="stampalista",
            name="titolo_y_mm",
            field=models.FloatField(
                default=0.0, help_text="Posizione Y titolo (mm, da top)"
            ),
        ),
    ]
