# Generated by Django 4.2.16 on 2025-10-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafiche", "0004_anagrafica_codice"),
        ("documenti", "0002_alter_protocollocounter_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AVVISO", "Avviso scadenza"),
                            ("DOCUMENTI", "Invio documenti"),
                            ("INFORMATIVA", "Comunicazione informativa"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("oggetto", models.CharField(max_length=255)),
                ("corpo", models.TextField(blank=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "data_invio",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "mittente",
                    models.EmailField(
                        blank=True,
                        help_text="Email mittente (default: impostazioni sistema)",
                        max_length=254,
                    ),
                ),
                (
                    "destinatari",
                    models.TextField(
                        help_text="Lista destinatari separati da virgola (email/pec)"
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("inviata", "Inviata"),
                            ("errore", "Errore invio"),
                        ],
                        db_index=True,
                        default="bozza",
                        max_length=20,
                    ),
                ),
                ("log_errore", models.TextField(blank=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente destinatario principale, opzionale se invio multiplo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicazioni",
                        to="anagrafiche.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicazione",
                "verbose_name_plural": "Comunicazioni",
                "ordering": ["-data_creazione"],
            },
        ),
        migrations.CreateModel(
            name="AllegatoComunicazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comunicazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allegati",
                        to="comunicazioni.comunicazione",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicazioni_allegato",
                        to="documenti.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allegato comunicazione",
                "verbose_name_plural": "Allegati comunicazione",
                "unique_together": {("comunicazione", "documento")},
            },
        ),
    ]
