# Generated by Django 4.2.16 on 2025-11-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0004_alter_documento_cliente_and_more'),
        ('protocollo', '0004_movimentoprotocollo_fascicolo_and_more'),
        ('comunicazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicazione',
            name='direzione',
            field=models.CharField(choices=[('IN', 'Entrata'), ('OUT', 'Uscita')], db_index=True, default='OUT', help_text='Direzione della comunicazione ai fini del protocollo.', max_length=3),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='documento_protocollo',
            field=models.ForeignKey(blank=True, help_text='Documento da protocollare per questa comunicazione.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicazioni_protocollo', to='documenti.documento'),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='protocollo_movimento',
            field=models.OneToOneField(blank=True, help_text='Movimento di protocollo collegato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicazione', to='protocollo.movimentoprotocollo'),
        ),
    ]
