# Generated by Django 4.2.16 on 2025-11-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_emailcontatto_mailinglist_mailinglistmembership_and_more'),
        ('comunicazioni', '0002_comunicazione_direzione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cartella', models.CharField(default='INBOX', max_length=120)),
                ('usa_ssl', models.BooleanField(default=True)),
                ('usa_starttls', models.BooleanField(default=False)),
                ('attiva', models.BooleanField(default=True)),
                ('filtra_da', models.TextField(blank=True, help_text='Elenco di indirizzi mittente consentiti (uno per riga). Lascia vuoto per accettare tutti.')),
                ('escludi_da', models.TextField(blank=True, help_text='Indirizzi mittente da escludere (uno per riga).')),
                ('soggetto_contiene', models.TextField(blank=True, help_text='Importa solo se il soggetto contiene almeno una delle parole chiave (una per riga).')),
                ('ultimi_uid', models.CharField(blank=True, max_length=120)),
                ('ultima_lettura', models.DateTimeField(blank=True, null=True)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('salva_headers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Casella IMAP',
                'verbose_name_plural': 'Caselle IMAP',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='contatti_destinatari',
            field=models.ManyToManyField(blank=True, related_name='comunicazioni_destinatari', to='anagrafiche.emailcontatto'),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Message-ID originale se importata da casella email.', max_length=255),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='import_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='importato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='liste_destinatari',
            field=models.ManyToManyField(blank=True, related_name='comunicazioni_destinatari', to='anagrafiche.mailinglist'),
        ),
        migrations.CreateModel(
            name='EmailImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=120)),
                ('message_id', models.CharField(max_length=255)),
                ('mittente', models.CharField(blank=True, max_length=255)),
                ('destinatari', models.TextField(blank=True)),
                ('oggetto', models.CharField(blank=True, max_length=500)),
                ('data_messaggio', models.DateTimeField(blank=True, null=True)),
                ('raw_headers', models.TextField(blank=True)),
                ('corpo_testo', models.TextField(blank=True)),
                ('corpo_html', models.TextField(blank=True)),
                ('importato_il', models.DateTimeField(auto_now_add=True)),
                ('errore', models.TextField(blank=True)),
                ('comunicazione', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_import', to='comunicazioni.comunicazione')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_imports', to='comunicazioni.mailbox')),
            ],
            options={
                'verbose_name': 'Email importata',
                'verbose_name_plural': 'Email importate',
                'ordering': ['-importato_il'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailimport',
            constraint=models.UniqueConstraint(fields=('mailbox', 'message_id'), name='uniq_mailbox_message_id'),
        ),
    ]
