# Generated by Django 4.2.16 on 2025-11-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0003_mailbox_comunicazione_contatti_destinatari_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateComunicazione",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("oggetto", models.CharField(max_length=255)),
                (
                    "corpo_testo",
                    models.TextField(
                        blank=True,
                        help_text="Testo email (plain text), può contenere variabili es. {{ nome_cliente }}",
                    ),
                ),
                (
                    "corpo_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML email (opzionale), può contenere variabili es. {{ nome_cliente }}",
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template comunicazione",
                "verbose_name_plural": "Template comunicazioni",
                "ordering": ["-data_modifica"],
            },
        ),
        migrations.CreateModel(
            name="FirmaComunicazione",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "corpo_testo",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Contenuto firma in plain text, può contenere variabili es. {{ operatore.get_full_name }}"
                        ),
                    ),
                ),
                (
                    "corpo_html",
                    models.TextField(
                        blank=True,
                        help_text="Contenuto firma HTML (opzionale), può contenere variabili come nel testo.",
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Firma comunicazione",
                "verbose_name_plural": "Firme comunicazioni",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="comunicazione",
            name="corpo_html",
            field=models.TextField(blank=True, help_text="Versione HTML del messaggio, opzionale."),
        ),
        migrations.AddField(
            model_name="comunicazione",
            name="firma",
            field=models.ForeignKey(
                blank=True,
                help_text="Firma applicata alla comunicazione.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comunicazioni",
                to="comunicazioni.firmacomunicazione",
            ),
        ),
        migrations.AddField(
            model_name="comunicazione",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template utilizzato per generare il contenuto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comunicazioni",
                to="comunicazioni.templatecomunicazione",
            ),
        ),
    ]
