# Generated by Django 4.2.16 on 2025-11-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0004_templatecomunicazione_firmacomunicazione_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicazione",
            name="dati_template",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TemplateContextField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=100, verbose_name="Chiave variabile")),
                ("label", models.CharField(max_length=120, verbose_name="Etichetta")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Testo (breve)"),
                            ("textarea", "Testo (multilinea)"),
                            ("integer", "Numero intero"),
                            ("decimal", "Numero decimale"),
                            ("date", "Data"),
                            ("datetime", "Data e ora"),
                            ("boolean", "Booleano"),
                            ("choice", "Scelta singola"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Tipo campo",
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="Richiesto")),
                ("help_text", models.TextField(blank=True)),
                ("default_value", models.TextField(blank=True)),
                ("choices", models.TextField(blank=True, help_text="Per le scelte singole, una opzione per riga. Facoltativo: valore|etichetta.")),
                (
                    "source_path",
                    models.CharField(
                        blank=True,
                        help_text="Percorso attributo da `comunicazione`, es. anagrafica.ragione_sociale",
                        max_length=200,
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="Ordine")),
                ("active", models.BooleanField(default=True, verbose_name="Attivo")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_fields",
                        to="comunicazioni.templatecomunicazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo variabile template",
                "verbose_name_plural": "Campi variabili template",
                "ordering": ["template", "ordering", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="templatecontextfield",
            constraint=models.UniqueConstraint(fields=("template", "key"), name="uniq_template_context_key"),
        ),
    ]
