# Generated by Django 5.2.8 on 2025-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0005_templatecontextfield_comunicazione_dati_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatecontextfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Testo (breve)"),
                    ("textarea", "Testo (multilinea)"),
                    ("integer", "Numero intero"),
                    ("decimal", "Numero decimale"),
                    ("date", "Data"),
                    ("datetime", "Data e ora"),
                    ("boolean", "Booleano"),
                    ("choice", "Scelta singola"),
                    ("codice_tributo", "Codice Tributo F24"),
                ],
                default="text",
                max_length=20,
                verbose_name="Tipo campo",
            ),
        ),
    ]
