# Generated by Django 5.2.8 on 2025-11-25 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0006_alter_templatecontextfield_field_type"),
        ("documenti", "0007_documento_popola_ubicazione"),
        ("fascicoli", "0007_alter_fascicolo_stato"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="allegatocomunicazione",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="allegatocomunicazione",
            name="data_creazione",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="allegatocomunicazione",
            name="fascicolo",
            field=models.ForeignKey(
                blank=True,
                help_text="Fascicolo da allegare come ZIP dei suoi documenti",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunicazioni_allegato",
                to="fascicoli.fascicolo",
            ),
        ),
        migrations.AddField(
            model_name="allegatocomunicazione",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="File caricato direttamente senza creare un Documento",
                null=True,
                upload_to="comunicazioni/allegati/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="allegatocomunicazione",
            name="nome_file",
            field=models.CharField(
                blank=True, help_text="Nome originale del file caricato", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="allegatocomunicazione",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="allegatocomunicazione",
            name="documento",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento esistente da allegare",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunicazioni_allegato",
                to="documenti.documento",
            ),
        ),
        migrations.AddConstraint(
            model_name="allegatocomunicazione",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("documento__isnull", False),
                    ("fascicolo__isnull", False),
                    ("file__isnull", False),
                    _connector="OR",
                ),
                name="allegato_almeno_uno",
            ),
        ),
    ]
