# Generated by Django 5.2.8 on 2025-11-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0007_add_allegati_fields"),
    ]

    operations = []
