# Generated by Django 5.2.8 on 2025-11-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0008_remove_anagrafica_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comunicazione",
            name="anagrafica",
        ),
    ]
