# Generated by Django 5.2.8 on 2025-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0009_remove_comunicazione_anagrafica"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatecontextfield",
            name="format_string",
            field=models.CharField(
                blank=True,
                help_text="Formato di visualizzazione. Esempi: Per date: '%d/%m/%Y' o '%d %B %Y'. Per decimali: '%.2f' (2 decimali) o '{:,.2f}' (con separatore migliaia). Per interi: '{:,d}' (con separatore migliaia). Per testo: '{:.50}' (max 50 caratteri).",
                max_length=100,
                verbose_name="Formato",
            ),
        ),
    ]
