# Generated by Django on 2025-11-28 00:00
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0011_emailimportblacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name='emailimport',
            name='raw_message',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='emailimport',
            name='stato_import',
            field=models.CharField(default='nuovo', max_length=30),
        ),
        migrations.AddField(
            model_name='emailimport',
            name='processato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailimport',
            name='processato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='email_import_processati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunicazione',
            name='bloccata',
            field=models.BooleanField(default=False),
        ),
    ]
