# Generated by Django 5.2.8 on 2025-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0012_emailimport_raw_and_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicazione",
            name="stato",
            field=models.CharField(
                choices=[
                    ("bozza", "Bozza"),
                    ("inviata", "Inviata"),
                    ("errore", "Errore invio"),
                    ("ricevuta", "Ricevuta"),
                ],
                db_index=True,
                default="bozza",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="templatecontextfield",
            name="format_string",
            field=models.CharField(
                blank=True,
                help_text="Formato di visualizzazione. Esempi: Per date: '%d/%m/%Y' o '%d %B %Y'. Per decimali: '{:,.2f}' (formato US: 1,234.56) o '{:,.2f}it' (formato IT: 1.234,56). Per interi: '{:,d}' (con separatore migliaia). Per testo: '{:.50}' (max 50 caratteri).",
                max_length=100,
                verbose_name="Formato",
            ),
        ),
    ]
