# Generated by Django 4.2.16 on 2025-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicazioni", "0013_alter_comunicazione_stato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatecontextfield",
            name="widget",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Rendering del campo: vuoto=default, 'anagrafica'=select Anagrafica. Usare con tipo_dato 'integer' per salvare l'ID dell'anagrafica.",
                max_length=32,
                verbose_name="Widget",
            ),
        ),
        migrations.AlterField(
            model_name="templatecontextfield",
            name="source_path",
            field=models.CharField(
                blank=True,
                help_text="Percorso attributo da `comunicazione`, es. get_prima_anagrafica.ragione_sociale",
                max_length=200,
            ),
        ),
    ]
